mooltipass/moolticute

src/Common.cpp

Should make dates display correctly

Date conversion correction

---

src/MainWindow.ui

It seems that how Moolticute is written change one may wants to get
the same things everywhere: Multicute -> Moolticute ?

<MainWindow: Change how Moolticute is written>

---

src/Common.cpp

Date handle correction

---

src/MPDevice.cpp
src/MPDevice.h
src/MPNode.cpp
src/MPNode.h

PR for Work in Progress

---

Makefile
src/MainWindow.cpp
src/WSServerCon.cpp

Fixing code style of previous commits.

Code style fixes

---

src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui

Set the files tab visible by default and keep the ssh keys tabs visible on demand or allways behaviour

Change files tab and the ssh keys tabs visibility options

---

gui.pro
lang.qrc
lang/mc_ru.ts
src/QSimpleUpdater/src/Downloader.cpp
src/QSimpleUpdater/src/Updater.cpp

Added translation files to russian. Translations is not full for now.

Russian translation and fixes for compiling errors

---

src/PasswordLineEdit.cpp

Using the AppGui awesome instance instead of creating a new one.

---

src/ServiceItem.cpp

Attempts to fix #115
please test it

Making Service Items Case Sensitive.

---

src/CredentialsManagement.cpp
src/MPDevice.cpp

Lift mandatory login limitation.

---

src/CredentialModel.cpp
src/CredentialModel.h
src/CredentialsManagement.cpp
src/CredentialsManagement.ui
src/LoginItem.cpp
src/TreeItem.cpp
src/TreeItem.h

FIX #142 still missing the fix for the missing update date.

Fix wrong date texts in the UI.

---

docker-compose.yml
scripts/ci/funcs.sh
scripts/ci/linux/after_success.sh
scripts/ci/linux/appimage.sh
scripts/ci/linux/appimage_functions.sh

It was tested with all the windows and osx builds disabled.

Pack Moolticute as an AppImage

---

scripts/ci/linux/appimage.sh

Copy dependencies recursively

---

lang/mc_de.ts
lang/mc_fr.ts
lang/mc_ru.ts
src/AppGui.cpp

This one typo has driven me insane, hahah.

Fixing a typo

---

src/DbBackupsTrackerController.cpp
src/FilesManagement.cpp
src/FilesManagement.h
src/FilesManagement.ui
src/WSClient.cpp
src/WSClient.h

Fix file quick access

---

README.md

Fedora linux specific instructions to compile moolticute.

Added dependency and compile instructions for Fedora

---

src/FilesManagement.cpp

Fix Issue 182

---

src/FilesManagement.cpp
src/FilesManagement.h

Exiting immediately when clicked discard deletions with no deletions pending

---

src/CredentialView.cpp

Solves issue #190 
Do you want to also disable the default expansion of the first service item ?

Expand services with logins marked as favorite.

---

src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui

Implements #178 
THIS IS A WORK IN PROGRESS DO NOT MERGE

Help popups.

---

src/MPDevice_emul.cpp

Simple GET_CUR_CARD_CPZ support

---

src/MPDevice_emul.cpp

simple SET_DATE support and small reordering

---

data/moolticute.sh

Use udev rules from github.com/bobsaintcool/mooltipass-udev/

---

gui.pro
src/AppGui.cpp
src/AppGui.h
src/DbBackupChangeNumbersComparator.cpp
src/DbBackupChangeNumbersComparator.h
src/DbBackupsTracker.cpp
src/DbBackupsTracker.h
src/DbBackupsTrackerController.cpp
src/DbBackupsTrackerController.h
src/DbExportsRegistry.cpp
src/DbExportsRegistry.h
src/DbExportsRegistryController.cpp
src/DbExportsRegistryController.h
src/MainWindow.cpp
src/MainWindow.h
tests/DbBackupsTrackerTests.cpp
tests/TestDbExportsRegistry.cpp
tests/TestDbExportsRegistry.h
tests/main.cpp
tests/tests.pro

Reminder to export database when no saves have been done for a month.

---

lang/mc_br.ts
lang/mc_de.ts
lang/mc_fr.ts
lang/mc_ja.ts
lang/mc_nl.ts
lang/mc_pt.ts
lang/mc_ru.ts
lang/mc_sv.ts
lang/mc_tr.ts
src/DbBackupsTrackerController.cpp

loose -> lose when its used to say that something may be unrecoverable.

<Fix some typos>

---

src/AppGui.cpp

handle status change, and show window if unknown smartcard.

feature request: display app when unknown card is inserted #204

---

src/MPDevice.cpp
src/MainWindow.cpp

Please test it,
I'm not sure if it's already implemented the defaultProgressCb when changing the credentials passwords.

Disconnect from progressChanged until the credentials changes are completed.

---

src/CredentialsManagement.cpp
src/CredentialsManagement.h

Fill the password field only if the credential is still selected.

---

src/AnimatedColorButton.cpp
src/AnimatedColorButton.h
src/CredentialsManagement.cpp
src/CredentialsManagement.h
src/CredentialsManagement.ui
src/MainWindow.ui
src/PasswordLineEdit.cpp

Part of issue #239 
Every discard changes button will get affected by this.

Cosmetic changes

---

src/AppDaemon.cpp
src/AppDaemon.h
src/WSServer.cpp

bind websocket by default to localhost

---

src/MainWindow.ui

Closes #242
Update URL in About tab

Update GitHub URL to the project in About tab

---

sysvinit/moolticuted

Add init script for SysV init based systems

add SysV init script

---

src/AnimatedColorButton.cpp
src/AnimatedColorButton.h
src/AnsiEscapeCodeHandler.h
src/AppDaemon.cpp
src/AppDaemon.h
src/AppGui.h
src/AsyncJobs.h
src/CredentialModel.cpp
src/DaemonMenuAction.cpp
src/DaemonMenuAction.h
src/DbExportsRegistry.h
src/HttpServer.cpp
src/LoginItem.cpp
src/LoginItem.h
src/MPDevice.cpp
src/MPDevice.h
src/MPDevice_win.cpp
src/MPManager.cpp
src/MPManager.h
src/MacUtils.mm
src/PromptWidget.h

I did some static analysis using Clang's scan-build and CppCheck.

Static analysis

---

README.md

Added the QtDBus dependency for Linux in the README

---

src/CredentialsManagement.ui

Enforce max length on passwords when in MMM

---

src/DbExportsRegistryController.cpp
src/FilesManagement.cpp
src/MainWindow.cpp
src/SSHManagement.cpp

fix #312:  Separately remember the last used dir for export, import, CSV import
Also, store the last used path for SSH key management and Files management.

312 default export folder

---

src/AppGui.cpp
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui

Fixing https://github.com/mooltipass/moolticute/pull/325

Implement Issue #257 White systray icon

---

.gitignore
data/moolticute.sh

since we don't use AppRun.c anymore (it's deprecated)

fix AppImage: specify path to our binary

---

win/installer.iss

It is added according to Inno Setup documentation:
http://www.jrsoftware.org/isfaq.php#env
http://www.jrsoftware.org/ishelp/index.php?topic=registrysection

#345 Adding cli to PATH in Inno Setup

---

gui.pro
src/CredentialModel.cpp
src/ParseDomain.cpp
src/ParseDomain.h
src/WSClient.cpp
src/WSServerCon.cpp

Needed to implement in WSServerCon and GUI side, because adding credential handled differently, when we are in MMM and not.

Fix adding manual credential subdomain/domain

---

src/MPDevice.cpp

Fixed cancel request incorrect command id.

#383 Fix Cancel_user_request commandId mapping

---

daemon.pro
src/HaveIBeenPwned.cpp
src/HaveIBeenPwned.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/WSClient.cpp
src/WSServerCon.cpp
src/WSServerCon.h

Added Have I Been Pwned password check for credential is stored or recalled.
**Note:** It is set to false by default, need to enable in settings

#402 Integrate hibp

---

src/MPDevice_linux.cpp
src/MPDevice_linux.h
src/MPDevice_mac.cpp
src/MPDevice_mac.h
src/MPManager.cpp
src/MPManager.h
src/UsbMonitor_linux.cpp
src/UsbMonitor_linux.h
src/UsbMonitor_mac.cpp
src/UsbMonitor_mac.h

Same handle, which was implemented for Windows in #422.
Handle adding/removing devices, instead enumerating devices every time.

Implemented linux hidraw add remove handle

---

src/BleDev.cpp
src/BleDev.h
src/BleDev.ui
src/Common.h
src/MPDevice.cpp
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MessageProtocol/MessageProtocolBLE.cpp
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

- Implemented UI changes:
- ![kép](https://user-images.githubusercontent.com/11043249/55589175-e7782180-572f-11e9-888d-5fc3b8b6931a.png)
- Added random bytes fetch

BLE dev tab adjustments, add fetch random data

---

src/FilesCache.cpp
src/FilesCache.h
src/MPDevice.cpp
src/MPDevice.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/MessageProtocol/IMessageProtocol.h
src/MessageProtocol/MessageProtocolBLE.cpp
src/MessageProtocol/MessageProtocolBLE.h
src/MessageProtocol/MessageProtocolMini.cpp
src/MessageProtocol/MessageProtocolMini.h
src/MooltipassCmds.h
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

Following commands were implemented:
- 0x000A / get change numbers
- 0x000B / Get card CPZ
- 0x0005: Cancel Request
- 0x000E / reset unknown card
- 0x000F / get # of available users
- Get number of available users was not implemented for mini too, so I added this to GUI on Advanced Tab and the user is able to get this information for BLE and Mini.
- 0x0010 / lock device
- 0x0011 / get status

Implement BLE commands

---

README.md

Some minor changes to the language used in README to make it more idiomatic and typos corrected.

Minor fixes to language and typos in README.

---

src/DbExportsRegistryController.cpp

#471 Fix grammatical mistake "for a while" vs "in a while"

---

src/MainWindow.ui

- Changed order for layout/language
- Changed some label name
- Enlarged layout/language comboboxes

[BLE] Device Settings UI changes

---

src/Common.cpp

#505 Add timestamp to logs

---

src/CredentialModel.cpp
src/CredentialsManagement.cpp

[BLE] MMM category related bug fixes

---

src/BleDev.cpp
src/BleDev.h
src/BleDev.ui
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MessageProtocol/MessageProtocolBLE.cpp
src/MooltipassCmds.h
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

`0x800E: Update Main & Aux MCU From Bundle` command was introduce for aux and main MCU flash.
BLE Tab:

[BLE] Use one Update Platform button instead of separate Aux and Main MCU Flash buttons

---

src/MPDeviceBleImpl.cpp

[BLE] #560 Set default category name for empty ones

---

src/MainWindow.cpp

#528 Reset settings on user logging in

---

src/AppGui.cpp

Update systray text on device connection

---

src/Common.cpp
src/Common.h

Add MMM status byte to MPStatus enum

---

src/CredentialModel.cpp
src/CredentialModel.h
src/CredentialsManagement.cpp
src/CredentialsManagement.h
src/CredentialsManagement.ui
src/LoginItem.cpp
src/MPDevice.cpp
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MessageProtocol/MessageProtocolBLE.h
src/Mooltipass/MPNode.cpp
src/Mooltipass/MPNodeBLE.cpp
src/Mooltipass/MPNodeBLE.h
src/Settings/SettingsGuiBLE.h
src/TreeItem.cpp
src/TreeItem.h

Implemented https://github.com/mooltipass/moolticute/issues/574.

[BLE] Add Key After Login/Password option to MMM

---

src/MPManager.cpp

Check connected devices for MP, when an other MP is disconnected

---

src/MainWindow.cpp

[BLE] Set user settings only visible, when user logged in

---

src/CredentialsManagement.ui
src/MainWindow.cpp
src/MainWindow.h

Decrease default window size on Mac

---

src/Common.h
src/MPDevice.cpp
src/MPDevice.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h

WIP, for review
Added support for webauthn credentials too and be able to handle further linked lists too.

#586 Handle BLE database model change

---

src/QSimpleUpdater/src/Updater.cpp

Updater use url to check extension instead of name in the updater*.json

---

src/Common.h

Ubuntu Xenial's default Qt package is 5.5.1: https://launchpad.net/ubuntu/xenial/+package/qt5-default
https://code.woboq.org/qt5/qtbase/src/corelib/global/qglobal.h.html#1197
https://doc.qt.io/qt-5/qtglobal.html#qOverload
> This function was introduced in Qt 5.7.

QOverload was added in Qt5.7, so add the implementation for bellow that version

---

src/MPDevice.cpp
src/MPDeviceBleImpl.h

[BLE] Fix category fetch related daemon crash

---

src/MPDevice.cpp
src/MPDevice.h
src/MPDevice_win.cpp
src/MPDevice_win.h

Fix MPDevice related this capture issues in singleShot calls

---

scripts/ci/funcs.sh

Create a copy of version.h to use it later during packeging (https://github.com/mooltipass/mc-dockers/pull/8)

Fix AppImage update issue

---

src/MainWindow.ui
src/Mooltipass/MPSettingsBLE.cpp
src/MooltipassCmds.h
src/Settings/DeviceSettings.cpp
src/Settings/DeviceSettings.h
src/Settings/DeviceSettingsBLE.cpp
src/Settings/DeviceSettingsBLE.h
src/Settings/DeviceSettingsMini.cpp
src/Settings/DeviceSettingsMini.h
src/Settings/SettingsGuiBLE.cpp
src/Settings/SettingsGuiHelper.cpp
src/Settings/SettingsGuiMini.cpp

[BLE] Add Lock Unlock and Display pin after back device settings

---

src/MPDevice.cpp
src/MessageProtocol/IMessageProtocol.h
src/MessageProtocol/MessageProtocolBLE.h
src/MessageProtocol/MessageProtocolMini.h
src/WSServerCon.cpp

CSV import support added from Advanced tab.

[BLE] Add CSV import implementation

---

src/MainWindow.ui

[BLE] Add tooltip for device settings

---

src/AppGui.cpp

#624 Fix AppImage start issue

---

src/DbExportsRegistry.cpp
src/DbExportsRegistryController.cpp

Fix for database popup displayed continuously, because MMMMode was not handled.

[BLE] Fix database popup issue

---

src/MainWindow.ui

Increase width of Keyboard Layout combobox

---

src/MainWindow.ui

Change text on About tab

---

daemon.pro
src/MPDevice.cpp
src/MPDevice_localSocket.cpp
src/MPDevice_localSocket.h
src/MPManager.cpp
src/MPManager.h
src/WSClient.cpp
src/WSServer.cpp
src/WSServer.h

Local sockets implementation from #488 with handling MP device connection/disconnection and add notification, when emulator is running and a device is connected.

Add emulator support

---

src/MPDevice.cpp

[BLE] #644 Remove cpzCtr check for ble during database import

---

src/FilesManagement.cpp
src/MPDevice.cpp
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MessageProtocol/IMessageProtocol.h
src/MessageProtocol/MessageProtocolBLE.cpp
src/MessageProtocol/MessageProtocolBLE.h
src/MessageProtocol/MessageProtocolMini.cpp
src/MessageProtocol/MessageProtocolMini.h
src/Mooltipass/MPNodeBLE.cpp
src/MooltipassCmds.cpp
src/MooltipassCmds.h
src/WSServerCon.cpp

- Enabled Files tab
- Implemented Files Management Mode for BLE
- Added and implemented the following commands
- MPCmd::WRITE_DATA_FILE
- MPCmd::READ_DATA_FILE
- Disable update file button for BLE
- Update service/file name when an other file is selected

[BLE] Implement small file storage

---

src/UsbMonitor_mac.cpp
src/UsbMonitor_mac.h

[BLE] Fix bluetooth first connection issue

---

src/QSimpleUpdater/src/Downloader.cpp
src/QSimpleUpdater/src/Downloader.h

Implement retry for MC update download

---

src/Common.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/PasswordLineEdit.cpp

Implemented #687 
New setting:

#687 Add option for default password length

---

src/Mooltipass/MPSettingsBLE.cpp
src/Settings/DeviceSettings.cpp
src/Settings/DeviceSettings.h
src/Settings/DeviceSettingsBLE.cpp
src/Settings/DeviceSettingsBLE.h
src/Settings/DeviceSettingsMini.h
src/Settings/SettingsGuiBLE.cpp

[BLE] Add tutorial enabled device setting for ble too

---

src/MainWindow.ui

Move Enable device tutorial to end of Miscellaneous device settings

---

src/MainWindow.cpp
src/PromptWidget.cpp
src/PromptWidget.h

[BLE] Fix Memory Management Error remains after entering Credentials Management Mode

---

src/MPDevice.cpp
src/MPDevice.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/WSServerCon.cpp

[BLE] Skip credential check during import csv

---

src/MainWindow.ui

Move Miscellaneous items to Advanced Settings group

---

src/DbExportsRegistryController.cpp
src/MainWindow.cpp
src/PromptWidget.cpp
src/PromptWidget.h

Fix for #559 
Stop displaying the database backup prompt for the user in MMM.

#559 Prevent database backup in MMM

---

src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/Settings/SettingsGuiBLE.cpp
src/Settings/SettingsGuiHelper.cpp
src/Settings/SettingsGuiHelper.h
src/Settings/SettingsGuiMini.cpp

Implemented https://github.com/mooltipass/moolticute/issues/735 for BLE.

[BLE] Add new No Password Input Prompt device setting

---

src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui

Moved No Password Input Prompt checkbox:

[BLE] #735 Fix build issue, move No Password Input Prompt

---

src/MainWindow.ui

Capitalize first letters of words in the settings panel

---

src/MPDevice.cpp
src/MPDevice.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.ui
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp
src/WSServerCon.h

[BLE] Implement process and display battery percent

---

src/MPDevice.cpp

#700 Store UTC time on device

---

src/CredentialsManagement.ui

[BLE] Fix position of TOTP Credential button in MMM

---

src/MPDevice.cpp
src/MPDeviceBleImpl.cpp
src/Mooltipass/MPMiniToBleNodeConverter.cpp

Replace some QByteArray append calls for backward compatibility with older Qt version

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

[BLE] Display Bundle Version on About Tab

---

src/Mooltipass/MPMiniToBleNodeConverter.cpp

Change remained appends from #751

Replace remaining QByteArray append calls for backward compatibility

---

src/WSServerCon.cpp

#705 Send empty list when there are no files cached

---

src/WSServerCon.cpp

Display "Please enter file management mode to list the files in your device." when cache is missing:

Inform user when cache is missing from Files Management

---

src/MainWindow.cpp

[BLE] #768 Enable tabs after importing DB

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/MessageProtocol/MessageProtocolBLE.cpp
src/MooltipassCmds.h
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

[BLE] Add NiMH Reconditioning start to Advanced Tab

---

src/BleCommon.h
src/Common.cpp
src/Common.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/MessageProtocol/MessageProtocolBLE.cpp
src/MooltipassCmds.h
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

[BLE] Add Authentication Security Challenge

---

src/MainWindow.ui

[BLE] Add margin for battery icon on UI

---

src/MainWindow.ui
src/Mooltipass/MPSettingsBLE.cpp
src/Settings/DeviceSettings.cpp
src/Settings/DeviceSettings.h
src/Settings/DeviceSettingsBLE.cpp
src/Settings/DeviceSettingsBLE.h
src/Settings/DeviceSettingsMini.cpp
src/Settings/DeviceSettingsMini.h
src/Settings/SettingsGuiBLE.cpp
src/Settings/SettingsGuiMini.cpp

[BLE] Add Hash Display setting on MC side

---

src/Mooltipass/MPSettingsBLE.cpp
src/Mooltipass/MPSettingsBLE.h

[BLE] Sending every parameter to GUI when fetched first time

---

src/BleDev.cpp
src/BleDev.h
src/DeviceDetector.h
src/MainWindow.cpp
src/WSClient.cpp
src/WSServerCon.cpp
src/WSServerCon.h

[BLE] Allow bundle upload when connected through USB and more than 60% battery

---

src/MPDevice.cpp
src/MPDevice.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h

When MC is running and bluetooth is enabled on the device the first message have not received response on Linux. This timeout is fixing it.

[BLE] Implement a timeout for the first message sent when BLE connected with bluetooth

---

src/FilesManagement.cpp
src/MPDevice.cpp
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MessageProtocol/MessageProtocolBLE.cpp
src/MooltipassCmds.h
src/WSServerCon.cpp

Fetching is implemented with the new 0x0031: Get Next Data Node Address & Name command.

[BLE] Fetch data nodes on Files tab instead of using cache

---

src/MPDevice.cpp

[BLE] Exit MMM on computer lock

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

[BLE] #803 Only allow save settings if every settings are fetched from device

---

src/MainWindow.ui
src/WSClient.cpp

Rename changed settings Reset to Cancel Changes

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

Added waiting screen, when NiMH Recondition started:
Display NiMH Recondition time:

[BLE] Implement NiMH Recondition changes

---

src/CredentialsManagement.cpp

[BLE] User cannot modify existing TOTP Credential

---

gui.pro
src/Common.h
src/CredentialModel.cpp
src/CredentialModel.h
src/FidoManagement.cpp
src/FidoManagement.h
src/FidoManagement.ui
src/MPDevice.cpp
src/MPDevice.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/Mooltipass/MPNode.cpp
src/Mooltipass/MPNode.h
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

FIDO Credentials page:
After entering FIDO management:
After removing a FIDO credential:

[BLE] Implement FIDO Credentials tab

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/Settings/DeviceSettingsBLE.cpp
src/Settings/DeviceSettingsBLE.h
src/WSServerCon.cpp

Added a `Reset default values` button, which is reseting settings values.

[BLE] Implement reset to default setting values option, fix #823

---

src/MainWindow.cpp

When there are duplicate credentials in the file only processing the first one.
If the duplicate entries contain different password, display a warning dialog:

Remove duplicate entries during CSV import

---

src/FilesManagement.cpp
src/FilesManagement.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MessageProtocol/MessageProtocolBLE.cpp
src/MooltipassCmds.h
src/NotesManagement.cpp
src/NotesManagement.h
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp

Implemented for BLE with >= 1 bundle version.
Delete file:
Delete note:

[BLE] Add quick delete note/file option

---

src/MainWindow.ui

[BLE] Change order of tabs, rename Fido to Fido2 tab name

---

src/FidoManagement.cpp
src/FidoManagement.ui

[BLE] Change Fido texts to Fido2

---

src/MPDevice.cpp
src/MainWindow.cpp

This way cleaned credential-login pair is checked. 
Remove duplicates.

Move CSV duplicate check logic to daemon

---

src/CredentialsManagement.cpp
src/CredentialsManagement.h
src/CredentialsManagement.ui
src/LoginItem.cpp
src/LoginItem.h
src/MPDevice.cpp
src/Mooltipass/MPNodeBLE.cpp
src/Mooltipass/MPNodeBLE.h

TOTP delete:
TOTP delete and create new one:

[BLE] Implement TOTP deletion, fix #855

---

scripts/ci/osx/Info.plist
scripts/ci/osx/after_success.sh

Add `NSRequiresAquaSystemAppearance true` for disable dark mode.

Copy Info.plist after MacOs build

---

src/MPDevice.cpp
src/MPDevice.h
src/MainWindow.cpp
src/Mooltipass/MPBLEFreeAddressProvider.h
src/WSServerCon.cpp

Implemented integrity check for BLE and updated test cases for it.

[BLE] Implement Integrity Check

---

src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui

Add User Manual links to About tab, fix #792

---

src/AppGui.cpp
src/MainWindow.cpp
src/MainWindow.h

Display notification when battery is below 30% and not charging.

Display warning notification when battery is low, fix #801

---

src/Common.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui

[BLE] Inform user when bundle version is outdated, fix #896

---

src/WindowLog.cpp
src/WindowLog.h
src/WindowLog.ui

Add option to save daemon logs to file

---

src/BleDev.cpp
src/DeviceDetector.h
src/MainWindow.cpp

Change ctrl + click to shift + click due to the mac issue. (ctrl + click is right click on Mac)

[BLE] Force select bundle with shift + click instead of ctrl

---

src/MainWindow.cpp
src/TutorialWidget.cpp
src/TutorialWidget.h

- Red frame
- Exit tutorial with ESC button press
- Increase tutorial font size
- Decrease spacing between title and text

[BLE] Improve Moolticute tutorial

---

src/TutorialWidget.cpp
src/TutorialWidget.h

[BLE] Tutorial UI changes

---

src/SystemNotifications/SystemNotificationWindows.cpp
src/SystemNotifications/SystemNotificationWindows.h

Implemented solution from https://stackoverflow.com/questions/53407374/is-there-a-way-to-detect-changes-in-focus-assist-formerly-quiet-hours-in-windo/53411482#53411482

Detect Focus Assist for Windows

---

src/MPDevice.cpp

Repro steps in #706 
During renaming credential addChildToDB call for the newNode fails, because the deleted node has not been removed yet.
Later deleted credentials are processed and a check for the potentially changed nodes handled here.

Fix delete and rename account to the same name in MMM, fix #706

---

src/CredentialsManagement.cpp

Enable to rename login to empty string in MMM, fix #917

---

src/CredentialsManagement.cpp
src/CredentialsManagement.h

Prevent changing login name to an existing one in MMM

---

src/Common.cpp
src/SSHManagement.cpp

Issue was introduced in https://github.com/mooltipass/moolticute/pull/985

Fix mc-agent lookup on Windows

---

src/Common.h
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.ui
src/Mooltipass/MPSettingsBLE.cpp
src/Settings/DeviceSettingsBLE.h
src/Settings/SettingsGuiBLE.cpp
src/Settings/SettingsGuiBLE.h
src/Settings/SettingsGuiHelper.cpp
src/Settings/SettingsGuiMini.cpp
src/WSServerCon.cpp

Implement force subdomain options
Change order of new Device Settings:

BLE Device Settings improvements

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MessageProtocol/MessageProtocolBLE.cpp
src/MooltipassCmds.h
src/WSServerCon.cpp

Implemented GET_TOTP_CODE (0x0041) command on daemon side.
Message "get_totp_code" is processed with "service", "login" data and totp code is sent back with "totp_code" data.

[BLE] Implement Get TOTP code command

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/MessageProtocol/MessageProtocolBLE.cpp
src/MooltipassCmds.h
src/Settings/SettingsGuiBLE.cpp
src/Settings/SettingsGuiHelper.cpp
src/Settings/SettingsGuiHelper.h
src/Settings/SettingsGuiMini.cpp
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp
src/WSServerCon.h

[BLE] Add Device Bluetooth Name device setting support

---

lang/mc_br.ts
lang/mc_de.ts
lang/mc_fr.ts
lang/mc_hu.ts
lang/mc_ja.ts
lang/mc_nl.ts
lang/mc_pt.ts
lang/mc_ru.ts
lang/mc_sv.ts
lang/mc_tr.ts
src/MainWindow.cpp

Improve readability of what is a key combination by putting it inside brackets and removing useless spaces.
Add the missing entry of Ctrl+Alt+Del without unlock.
Update the whole french translation.

Fix issue #1052 and update french translation

---

src/Common.h
src/CredentialModel.cpp
src/CredentialModel.h
src/CredentialsManagement.cpp
src/CredentialsManagement.h
src/ItemDelegate.cpp
src/ItemDelegate.h
src/LoginItem.cpp
src/MPDevice.cpp
src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MessageProtocol/MessageProtocolBLE.h
src/Mooltipass/MPNode.cpp
src/Mooltipass/MPNodeBLE.cpp
src/Mooltipass/MPNodeBLE.h
src/ServiceItem.cpp
src/ServiceItem.h
src/WSClient.cpp
src/WSClient.h

[BLE] Implement multiple domains support

---

src/MainWindow.ui
src/Mooltipass/MPSettingsBLE.cpp
src/MooltipassCmds.h
src/Settings/DeviceSettingsBLE.cpp
src/Settings/DeviceSettingsBLE.h
src/Settings/SettingsGuiBLE.cpp
src/Settings/SettingsGuiBLE.h
src/Settings/SettingsGuiHelper.cpp
src/Settings/SettingsGuiMini.cpp

[BLE] Add switch off on lock setting

---

src/CredentialsManagement.cpp

Fix Qt6 MMM filter remove display issue

---

README.md

see[0].
[0] https://github.com/mooltipass/mooltipass-udev/pull/3#issuecomment-1329915978

Start working on doc for udev rule on non systemd linux

---

src/MainWindow.cpp
src/MainWindow.ui

To contain the version number:

[BLE] Change latest bundle version text

---

src/BleDev.cpp
src/DeviceDetector.h
src/MPDeviceBleImpl.cpp
src/MainWindow.cpp

Skip password, bundle check if ctrl key is pressed

[BLE] Improve NoBundle FW upload

---

src/MPDevice.cpp

Wrong function were used for setting data nodes during import.

[BLE] Fix import data nodes

---

src/BleDev.cpp
src/NotesManagement.cpp
src/NotesManagement.h

- Exit note editing mode when device is disconnected
- After adding note display the new note in correct alphabetical order

[BLE] Notes improvements

---

src/MainWindow.cpp
src/MainWindow.ui

[BLE] Remove Enabled/Disabled text for BT and Knock detection

---

src/NotesManagement.cpp
src/NotesManagement.h

[BLE] Decrease note images, increase font size, fix #1113

---

src/CredentialsManagement.cpp
src/CredentialsManagement.h
src/CredentialsManagement.ui

Apply changes from #1160 to credentials edit in MMM too:

Fix Login and Password length limit for credentials edit in MMM

---

src/AppGui.cpp
src/AppGui.h
src/BleDev.cpp
src/CredentialsManagement.cpp
src/CredentialsManagement.h
src/DbExportsRegistryController.cpp
src/FidoManagement.cpp
src/FilesManagement.cpp
src/MainWindow.cpp
src/MainWindow.h
src/SSHManagement.cpp
src/WindowLog.cpp

Prevent Linux Mint dark mode readability issues, fix #1158

---

src/MainWindow.ui

[BLE] Add improve battery life text to disable BLE setting, fix #980

---

src/CredentialsManagement.cpp

[BLE] Add right click link option

---

src/PasswordLineEdit.cpp
src/PasswordLineEdit.h

Add copy to clipboard for password generation, fix #1176

---

src/MainWindow.ui
src/Mooltipass/MPSettingsBLE.cpp
src/MooltipassCmds.h
src/Settings/DeviceSettingsBLE.cpp
src/Settings/DeviceSettingsBLE.h
src/Settings/SettingsGuiBLE.cpp
src/Settings/SettingsGuiBLE.h
src/Settings/SettingsGuiHelper.cpp
src/Settings/SettingsGuiMini.cpp

- Paranoid Pin Entry
- Disable Battery Charging

[BLE] Add new device settings

---

src/CredentialsManagement.cpp
src/CredentialsManagement.h

If password is fetched from a credential which has multiple domains, concatenate the first domain to service name before sending ask_password request.

[BLE] Fix fetch password for multiple domains from MMM

---

src/MPDeviceBleImpl.cpp
src/MPDeviceBleImpl.h
src/MainWindow.cpp
src/MainWindow.h
src/MainWindow.ui
src/WSClient.cpp
src/WSClient.h
src/WSServerCon.cpp
src/WSServerCon.h

Recondition simulation demo with continue enabled:
Recondition simulation demo without continue enabled:

[BLE] Add option to continue recondition

---

src/MPDevice.cpp
src/Mooltipass/MPBLEFreeAddressProvider.cpp

[BLE] Fix import freeze with full DB

---

README.md

Added Void Linux build instructions along with command to update udev rules for runit init system

Added Void Linux instructions

---

README.md

This includes instructions on building for Alpine Linux when used as a desktop

Added instructions for building on Alpine Linux

---

lang/mc_ru.ts

This PR fully reworks Russian translation for all of the settings present in the app, fixes typos present, perhaps adds new ones.

lang: Update russian translation

---

gui.pro
src/MainWindow.ui
src/NoScrollComboBox.cpp
src/NoScrollComboBox.h

Disable scroll on hover for all of the QComboBoxes in Device and App Settings.

[BLE] Disable scroll on hover for Settings lists

---

lang/mc_br.ts
lang/mc_de.ts
lang/mc_fr.ts
lang/mc_hu.ts
lang/mc_ja.ts
lang/mc_ko.ts
lang/mc_nl.ts
lang/mc_pt.ts
lang/mc_ru.ts
lang/mc_sv.ts
lang/mc_tr.ts

It seems that some strings were missing, so I took the liberty of running lupdate to sync all of the translations with the current source (commit 1) and later translate the remaining strings. 
The only thing's missing right now is the translation of the device firmware itself.

Synchronize all translations and update russian translation

---

src/SystemNotifications/SystemNotificationWindows.cpp
src/SystemNotifications/SystemNotificationWindows.h

Fix using SnoreToast from installed folder

---

src/FilesManagement.cpp
src/FilesManagement.ui
src/MPDeviceBleImpl.cpp

Fix progress bar for file upload
