mooltipass/moolticute

README.md
@raoulh I can compile moolticuted with those instructions on my raspi3 and start the app. However I still have no access to the device. I tried to run chromium with the official app that works. I used the special archlinux udev rule that is suggested in the official textfile. So there must be something still wrong in the udev rule I guess. Do you have any idea?
=> Added Arch Linux compile instructions

README.md, daemon.pro, src/AppDaemon.cpp, src/AppDaemon.h, src/HttpClient.cpp, systemd/moolticuted.service, udev/69-mooltipass.rules
The main work is related to removing the dependencies on XCB for the daemon on Linux.
I get in trouble when removing the widget QT modules by not beeing able to compile in some case so I change the:
```
#if defined(Q_OS_LINUX)
// ...
#else
//
#endif
```
into
```
#if defined(Q_OS_WIN) || defined(Q_OS_MAC)
// ..
#else
// ...
#endif
```
When this dependencies is removed one can integrate upstream a systemd service for running the daemon easily.
I also merge udev rules provided for Arch and ubuntu and think that it would works on every systemd based host.
=> Removing XCB dependencies from daemon on Linux

README.md, daemon.pro, udev/69-mooltipass.rules
This reverts commit 10b1a0b57181302ce42eeabad12399975a12e84f.
Udev rules moved into a dedicated repository https://github.com/bobsaintcool/mooltipass-udev
=> Revert "<udev: Add a udev rules that should benefit for systemd based system>"

README.md, daemon.pro, udev/69-mooltipass.rules
Only one instance of moolticute could be run at a time. It makes more
sense to move the systemd service file systemd wide.
=> Dev/systemd: Move the systemd service file systemd wide

src/MainWindow.ui
Change `in` to `is` in main GUI settings pane
=> Fix minor typo in main GUI

src/CredentialsManagement.ui
The credentials management window had an odd order for advancing between widgets using the ``tab`` key.
=> Fix tab stop order in credentials management window

src/CredentialsManagement.cpp, src/CredentialsModel.cpp, src/CredentialsModel.h, src/CredentialsView.cpp, src/CredentialsView.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui
1/ choisir par défaut le premier credential plutot que de laisser désactiver la partie de droite. Dans le cas d'une base de donnée vide, laisser tout désactivé à droite
2/ ajouter un racourci clavier (du type ctrl-a-d-f) pour afficher les tabs "Files" et "SSH Keys" (remarque: le shortcut est CTRL+SHIFT+F1)
=> Implemented:

src/MainWindow.cpp, src/MainWindow.ui
It allows to hide/show all labels with device information through changing visibility of widget. It also fix "%1" in device information labels at "About" page.
When you start gui application without an device connected, you can see this on "About" page:
=> Combine device information labels at one widget

src/MPDevice_linux.cpp, src/MPDevice_linux.h, src/MPManager.cpp, src/UsbMonitor_linux.cpp, src/UsbMonitor_linux.h
By adding a new thread for handling the libusb events loop when a device is connected the speed is increased to 27 kb/s while performing integrity check.
=> Adding a thread for the libusb events loop

systemd/moolticuted.service
This pull request adds a lot of hardening features to moolticuted systemd service.
The most important one is the execution as normal user instead of root. For this use, it requires good permissions defined on USB device (through given udev rule).
Others settings indicate unused features, to enforce their non-use in case of vulnerability.
=> Add hardening settings to systemd service

src/AnimatedColorButton.cpp, src/CredentialsManagement.cpp, src/CredentialsManagement.h
Fix for #116 
* Quick exit when "Discard all" clicked if no changes.
* Confirm current item changes if "Save all" clicked.
* Ask for confirmation on selected credential changed and select previus in case of cancelation.
=> Improve credentials changes management.

src/CredentialsManagement.cpp
=> Disable save button when saving credential and waiting for user approval on device

data/moolticute.desktop, data/moolticute.sh, scripts/ci/linux/appimage.sh
Add a wrapper script to install Udev rules if they don't exists.
Also allows uninstall, check rules, and run as daemon.
=> Appimage wrapper

src/DbBackupsTrackerController.cpp, src/DbBackupsTrackerController.h
Hide import and export messages when:
- the device is disconnected, 
- the card is removed or
- the current db backup file being track is changed.
=> Hide backup import and export messages 

src/DbBackupsTrackerController.cpp, src/DbBackupsTrackerController.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui
Backups tracking controls are hidden for devices with firmwares lower that "1.2"
An alphanumeric comparison is performed as the version number is an string.
Please check
=> db backups traking  only in firmwares equal or greater than 1.2

src/DbBackupsTrackerController.cpp
Fix #160
there was an error in the version number that i was using as base to show the import dialog.
The "v" was missing.
Please notice that this is a lexicographical comparison.
=> Correct minimum firmware version number to show the import dialog.

src/DbBackupsTrackerController.cpp, src/DbBackupsTrackerController.h
fix #166
The requests are shown every time a change is made credentials change numbers.
=> Hide previous import backup message before showing a new one.

src/MainWindow.cpp
=> Hide Generate MooltiApp Compatible File checkbox for unknown cards.

src/MooltipassCmds.h
=> fix for problem with sizeof(MPCmd::Command) #192

src/MPDevice_emul.cpp
**CHECK_PASSWORD:** return of `0x01` rpl.
**GET_FAVORITE:** starting of counter in cycle from `2` (not` 0`)
=> simple CHECK_PASSWORD support & GET_FAVORITE fix

daemon.pro, src/MPDevice_win.h, src/qwinoverlappedionotifier.cpp, src/qwinoverlappedionotifier.h
Qt removed qwinoverlappedionotifier_p.h from the Qt5.10 SDK. This fix adds the files qwinoverlappedionotifier_p.h, renamed qwinoverlappedionotifier.h and qwinoverlappedionotifier.cpp to the moolticute code base. Files downloaded from Qtserialport GitHub archive https://github.com/qt/qtserialport/tree/5.10/src/serialport.
These files are only included in the project from Qt 5.10 onwards.
=> Qt 5.10: private/qwinoverlappedionotifier_p.h: No such file or directory #201Issue 201

src/Common.h, src/CredentialModel.cpp, src/CredentialModel.h, src/CredentialModelFilter.cpp, src/CredentialModelFilter.h, src/CredentialView.cpp, src/CredentialView.h, src/CredentialsManagement.cpp, src/ItemDelegate.cpp, src/ItemDelegate.h, src/LoginItem.cpp, src/LoginItem.h, src/RootItem.cpp, src/RootItem.h, src/ServiceItem.cpp, src/ServiceItem.h, src/TreeItem.cpp, src/TreeItem.h
Fix for 207.
In debug mode it will eventually assert in QAbstractItemModelPrivate::removePersistentIndexData, while deleting a QPersistentModelIndex. This occurs while handling a mouse click immediately following a sort, in QItemSelectionModel::setCurrentIndex while a copy of the previous index is being deleted.
CredentialView :
Add code so view knows the current login item. 
Handle layoutchanged signal after sorting, so the current item can be reset to the previous value.
Show header and enable sorting. Activating old sort by name code and new sort by date code.
CredentialModelFilter:
Add sort by date to lessThan. 
Override sort virtual function to remember sort order for lessThan.
CredentialModel:
Change number of columns to 2.
Modify data to return update date for new column row, and …
=> feature request: in MMM, sort credentials by modified date feature request good first issue help wanted #207 

src/MainWindow.ui
prevent info icon from moving on app resize.
set database basck monitoring lable sizepolicy to preferred from expanding
=> minor cosmectic issue #229

src/CredentialsManagement.cpp
The locked view is being set only when the memMgmtModeChanged is triggered. This sometimes happens after the progress view is hidden.
So we set the lock screen view in the CredentialsManagement.ui after the save button is clicked.
=> Lock mmm screen when the save button is clicked

gui.pro, src/AppGui.cpp, src/AppGui.h, src/Common.cpp, src/DbBackupsTrackerController.cpp, src/DbBackupsTrackerController.h, src/DbExportsRegistryController.cpp, src/DbExportsRegistryController.h, src/DbMasterController.cpp, src/DbMasterController.h, src/MainWindow.cpp, src/MainWindow.h
Introduce DbMasterController  which is a coordinator for DbExportsRegistryController and DbBackupsTrackerController as they both tried to use the same MainWindow::promptWidget.
This class prevents situations when one class shows prompt for backup a database
and another immediately hides it.
=> fix appearing of monitored backup save requests

tests/DbBackupsTrackerTests.cpp
It didn't find the test data correctly when using a build folder, like "build/", not directly in the
root of the repository.
`SRCDIR` is defined in tests/tests.pro but DbBackupsTrackerTests.cpp used `__FILE__`.
Tests output excerpt before:
```
Totals: 8 passed, 10 failed, 0 skipped, 0 blacklisted
```
And after:
```
Totals: 18 passed, 0 failed, 0 skipped, 0 blacklisted
```
=> Fixed DbBackupsTrackerTests to correctly find test data

src/AppGui.cpp, src/CredentialModelFilter.h, src/ItemDelegate.h, src/MainWindow.cpp
Fixed some warnings:
- Unused `this` captured in lambda
- Added missing `override` keywords
- Marked `this` as unused on macOS since it is used on Windows and Linux
=> Fix warnings

src/MPDevice.cpp, src/MPDevice.h
In relation to talk about memory leaks (on IRC), I looked into what was captured in lambdas in "src/MPDevice.cpp" particularly. The leaks pertain to the fact that lots of the lambdas share multiple copies of data and state, which is compounded into multiple deeper levels. The depth is often a function of the size of the credentials database.
Reasons for not using `[=]`:
- It is unclear exactly what is captured
- In most cases more than necessary is captured, and thus also copied
Notes on the expanded capture list:
- It is longer to write but everyone (also new contributors) knows what data is needed for the scope
- Only what is needed is accessible, and in some cases only as references to avoid copies
I wanted to continue to expand captures in other files but decided that it was better …
=> Capture what is needed instead of everything in lambdas

scripts/ci/linux/script.sh, scripts/ci/osx/script.sh, src/ParseDomain.cpp, tests/TestParseDomain.cpp, tests/main.cpp
Changed so the success of the tests is reflected by the exit code of the program: the number of failed tests. Thus `0` is overall success.
Travis runs the tests right after compilation.
=> Run tests for Travis builds

src/MainWindow.cpp
Fixed by the simplest way possible, but there were other variants of fix that I'd like to mention here.
Daemon sends messages in the following order (listed with connected MainWindow slots):
"mp_connected"    -> updatePage()
"status_changed"  -> updatePage()
"version_changed" -> DBBackupController::handleFirmwareVersionChange() -> window->showDbBackTrackingControls(true/false)
But the problem was showDbBackTrackingControls() only stores a 'bool' flag. It didn't actually change visibility status of widgets.
So I just called updatePage() from showDbBackTrackingControls().
Currently, there is no recursion possible because showDbBackTrackingControls() is called only from handleFirmwareVersionChange() which is called only by a signal WSClient::fwVersionChanged(). To avoid any possible …
=> Fix ui: show monitored backup control for unknown card

src/MainWindow.ui
Clicking the link didn't do anything, but now it opens in a browser.
=> Open project link in browser on mouse click

src/MainWindow.cpp, src/MainWindow.h
fix UI: do not show 'backup monitoring' controls if 'unknown' card is inserted
=> fix UI: do not show 'backup monitoring' controls for 'unknown' card

src/Common.h, src/MainWindow.cpp, src/MainWindow.ui
Two behaviors can be configured in app settings:
1. Close App -> Correctly closes down app
2. Hide Window -> Hides window and doesn't close the app
Since no File->Quit menu action was defined before, ⌘+Q would abruptly terminate the app without
calling all deleters as expected.
=> Proper ⌘+Q behavior on Mac

gui.pro, src/MainWindow.cpp, src/MainWindow.h, src/SystemEventHandler.cpp, src/SystemEventHandler.h
This builds on top of the previous feature about locking the device if certain system events were detected. Since Linux has a lot of different ways of handling things, it's a best effort trying to support general events and certain ones from Ubuntu, GNOME, and KDE environments.
DBus is used to detect the events so on Linux the project now depends on the QtDBus module.
=> Lock device via Linux system events

src/SSHManagement.cpp, src/SSHManagement.ui
The improvements are based on the requests at [mc-agent #11](https://github.com/raoulh/mc-agent/issues/11#issuecomment-387362273).
=> SSH management improvements

src/DbBackupsTracker.cpp, src/DbBackupsTracker.h, src/DbBackupsTrackerController.cpp, src/DbExportsRegistryController.cpp, src/DbMasterController.cpp, src/DbMasterController.h, src/MainWindow.cpp, tests/DbBackupsTrackerTests.cpp, tests/DbBackupsTrackerTests.h
fix #318: fix WSClient::dbExported signal handling
Use the signal consistently: only a part of the program which requested an export should give the export results.
Fix typo SympleCrypt => SimpleCrypt to use 'SimpleCrypt' encryption instead of 'none' in periodic and auto-prompted exports.
=> 318 odd export behavior

src/MPDevice.cpp, src/MPDevice.h, src/MainWindow.cpp
WebSocket API was changed: parameter "knock_sensitivity":
old values:  0-low, 1-medium, 2-high
new values:  0-very low, 1-low, 2-medium, 3-high
=> fix #319: add new level of knock sensitivity: "Very Low"

src/AppDaemon.cpp
With QHostAddress::LocalHost there is a 30 secs delay until  we get the QWebSocketServer::newConnection signal, while with Any or LocalHostIPv6 it works instantly.
=> Fix issue #331 MacOS, "The Moolticute Daemon is Not Running"

src/AppGui.cpp, src/SystemEventHandler.cpp
Issues:
-timerDaemon was still running during destruction so it was possible that AppGui::searchDaemonTick()  was called with during that time
-~SystemEventHandler() had some issue, if I added a qDebug log, then it did no crashed anymore (maybe some timing issue). This was called after MainWindow's destructor finished. Crashed only in release build.
-Added Qt::QueuedConnection flag to quitAction for safer quit.
=> Fixing Windows release build

src/AppGui.cpp
* timerDaemon is not initialized when an instance is already running;
* currSocket: use 'deleteLater' as shown in http://doc.qt.io/qt-5/qtcore-ipc-localfortuneserver-server-cpp.html
code clean up: daemonAction is not unused
Note: in the current state GUI is unable to connect to the daemon
because daemon is listening on IPv6 interface, but GUI tries to connect via IPv4
after 844e09eca53d - this problem is out-of-scope or this PR
=> issue #324 fix crash on second instance run

src/AppGui.cpp
orderFrontRegardless was responsible on Mac to show the MainWindow on the top after it was hidden. However it crashed very often and even if it was not crashing, it hasn't brought the window in front.
It crashed because the used winId is changing during runtime, so it is dangerous to use it:
http://doc.qt.io/archives/qt-4.8/qwidget.html#winId
Instead of orderFrontRegardless the raise and activateWIndow call is bringing the MainWindow to the top level after clicking show without a crash.
=> Fixing crash on Mac from orderFrontRegardless

src/WSServer.cpp, src/WSServerCon.cpp, src/WSServerCon.h
I experienced this issue with the newest Qt version and compiler, there was no problem on the previous one and on Travis.
Function calls like "sendJsonMessage({{ "msg", "mp_disconnected" }});" causing compile error because of  the brace initialization calls.
=> Fixing build issue with newer compiler

lang.qrc
There is a mc_hu.ts translation file, but it is not included in lang.qrc so it is unavailable from the GUI.
=> Adding missing Hungarian language file

data/moolticute.sh
Without this fix moolticute.sh script tries to run /usr/bin/moolticute and fails: no such file
=> Add support for running extracted AppImage

data/moolticute.sh, src/AppGui.cpp, src/QSimpleUpdater/src/Updater.cpp
Appimage: search for root CA in different locations
Recently I digged in OpenSSL on how it loads root certificates.
While I was reading the code I noticed that OpenSSL understands environment variables,
so I decided to use this shortcut instead of patching OpenSSL.
Also, Updater in Moolticute was fixed to work with ".AppImage" suffix.
Here the results of testing on Ubuntu 18.10 live CD:
```
ubuntu@ubuntu:~/Downloads$ grep ssl moolticute.strace.log 
6247  openat(AT_FDCWD, "/tmp/.mount_MooltiHWvuAH/usr/bin/../lib/libssl.so.1.0.2k", O_RDONLY|O_CLOEXEC) = 14
^^^ OK, OpenSSL is loaded from AppImage
6247  openat(AT_FDCWD, "/tmp/.mount_MooltiHWvuAH/usr/lib/ssl/openssl.cnf", O_RDONLY) = 14
^^^ OK, OpenSSL config is read from AppImage
6247  openat(AT_FDCWD, "/etc/ssl/certs/", …
```
=> Appimage search for root CA in different locations

src/AppGui.cpp
During first start "settings/systray_icon" QSetting wasn't persisted, but the combobox reads the default value from this QSetting.
=> #354 Setting default systray option during first start

src/CredentialsManagement.cpp, src/CredentialsManagement.h, src/CredentialsManagement.ui
Added the new exit button:
It is presented until a change made regarding credentials (added, removed, modified, added to fav), after that the original save and discard is displayed.
=> #351 Adding exit button to Credentials management in clean state

src/MainWindow.cpp
Need to add the default true value for "settings/auto_start" in _on_pushButtonAutoStart_clicked_ function too.
The current behavior, when the user clicks Disable for the first time is the following:
After clicking Disable it is enabling AutoStart.
This default value solves the issue.
=> #349 Adding default true for auto_start in pushButtonAutoStart clicked

src/MPDevice.cpp
By the time the lambda is called the captured **pwdChangeJobs** pointer contains memory garbage. During _setCurrentJobError_ function it crashes.
In _runAndDequeueJobs()_ function **currentJobs** is set to the actual job, which is valid, when the lambda is called.
**Crash Repro**:
1. Go to Credentials
2. Enter Credentials Management Mode with Mooltipass device
3. Add a new credential with "Add or update a credential" section
4. Click Save all changes
5. Mooltipass device asks "Change Password For" if the user discards it or timeouts, then the daemon crashes, the user cannot use MC, until restarting the daemon and the added credential is saved with some invalid password (originaly it was "test" too):
6. ![kep](https://user-images.githubusercontent.com/11043249/47529879-5c098300-d8a9-11e8-97 …
=> Fixing crash after adding credential in MMM and discarding save password

src/AppGui.cpp, src/SystemNotifications/SystemNotificationWindows.cpp, src/SystemNotifications/SystemNotificationWindows.h
WinRT is not available on win7, so if the client wants to run SnoreToast it is getting an "_api-ms-win-core-winrt-l1-1-0.dll is missing_" error.
So on win7/win8 I implemented to send the simple notification through systray:
Also only checking if snoretoast is installed on win10.
=> #368 Sending simple system notification with systray bellow Win10

src/MainWindow.cpp
According to device code it requires the Password flag, and it is working right with that.
=> #363 Fixing Lock/Unlock Feature Ctrl + Alt + Del/ Win +L

src/WSClient.cpp
It caused a problem when we are not in Credentials Management Mode, fixed that case:
It is saving the service entered by the user, not depending on subdomain selection setting.
=> #378 Fixing cut subdomain during saving credentials

src/AppGui.cpp, src/AppGui.h, win/installer.iss
If autolaunch was enabled, then after OS start, the settings from the device were not loaded.
This was because in that case mainwindow wasn't created during startup, so when the daemon sent the parameter loaded signals, then the mainwindow could not process them.
=> #247 Develop247 device settings read fix

src/MainWindow.cpp, src/PromptWidget.cpp, src/PromptWidget.h
**Original issue:**
Enter Credentials Management Mode and deny it on the device. The app stucks at the waiting screen with a messagebox.
**Fix:**
Instead of the waiting screen and the message box, displaying the original credentials with a message prompt, when enter MMM is denied. According to the expected behavior described in #403.
The fix resolve the same issue on Files Management screen too.
I extended PromptWidget to support a simple information message with an OK button which hides the prompt.
=> #403 Fix MMM denied stuck

src/MainWindow.cpp
**getSaveFileName** is using native dialog:
"On Windows, Mac OS X and Symbian^3, this static function will use the native file dialog and not a QFileDialog."
On Linux it is not saving the choosen extension, so need to add it from code.
https://stackoverflow.com/questions/9822177/is-there-a-way-to-automatically-add-extensions-to-a-file-using-qfiledialog-on-li
=> #392 Add .bin extension to exported db file for Appimage

src/MainWindow.cpp
On device disconnect the serial number field is cleared.
However when we connect the other device the parameters only read after enter the pin finished, but the previously connected device's parameters are still represented in wsClient (gui side) so on the connect signal it is loading those outdated informations.
Fix: On device disconnect I reset these informations, so until enter the pin is presented it is displaying "None" on About tab.
=> Fix displaying previous device informations

src/BleDev.cpp, src/BleDev.h, src/MPDevice.cpp, src/MPDevice.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui, src/MessageProtocol/IMessageProtocol.h, src/MessageProtocol/MessageProtocolBLE.cpp, src/MooltipassCmds.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp
Rename the BLE Tab related platInfo functions to debug and added a new one for handling 0x0003 Get Platform Info command.
On GUI side, if BLE is detected Main and Aux MCU are also displayed:
=> #415 Display device informations for BLE on About tab

src/BleDev.cpp, src/BleDev.h, src/BleDev.ui, src/Common.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp
Added a "Acceleration Data Fetch" button to BLE Dev tab. When clicking it will open a prompt to save a binary file, then it is constantly saving data from the device to that binary file. 
Process can be stopped by clicking the same button, now renamed to "Stop Fetch"
=> Implement Acceleration Data Fetch for BLE Dev tab

data/moolticute.sh
AppImage: support executing mc-agent and mc-cli from a bundle with CLI args.
Examples are also added to --help text.
=> AppImage: support executing mc-agent and mc-cli from a bundle with CLI args

src/SSHManagement.cpp
SSH management: give a workaround for PuTTY users how to import their keys
(extend the text in the existing message box)
reference: https://github.com/raoulh/mc-agent/issues/11#issuecomment-448257045
=> SSH management: give a workaround for PuTTY users how to import their keys

src/MPDevice_win.cpp, src/MPDevice_win.h, src/MPManager.cpp, src/MPManager.h, src/UsbMonitor_win.cpp, src/UsbMonitor_win.h
On Windows when device is added or removed checkUsbDevices() is called. When there is an **exclusively opened device** it does not find the device again, because cannot open it for checking the product and vendor id, hence the MPDevice_win::enumerateDevices() function returns with an empty device list, so it disconnects every device.
The crash is caused by the delayed exitMemMgmtMode, when we are calling it the device has already disconnected because of the issue mentioned above.
Also added an option for exclusive device opening, because when we are only peaking the device's vendor and product id from attributes it does not require an exclusive opening.
If exclusive device opening will implemented for Linux or Mac we also need to check this issue and use this new handle for them too, if …
=> Implemented a new usb add&remove handle for exclusive device open crash fix on Windows

daemon.pro, src/BleCommon.h, src/MPDevice.cpp, src/MPDevice.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MessageProtocol/IMessageProtocol.h, src/MessageProtocol/MessageProtocolBLE.cpp, src/MessageProtocol/MessageProtocolBLE.h, src/MooltipassCmds.h, src/WSServerCon.cpp
- Implement store/get credential support for BLE on daemon side
- Currently not available from gui, but I left commented example usage in MPDevice.cpp:151
- Store a credential with service name, login, description, third field and password (**0x0006: Store Credential**)
- Get credential with service name and login (**0x0007: Get Credential**)
- Created a get_message interface to get and return the credential for a request from GUI
- Eliminated message timeout for BLE:
- Daemon is waiting until it does not receive the response for the message
- Handled the **checkReturn** option for messages, which does not require response from device. (E.g.: 0x8007: Reboot main MCU to Bootloader or 0x8009: Flash Aux MCU with Bundle Contents)
- **Known issue**: After Aux MCU Flash the usb is reconnecting …
=> Implement store/get credential support for BLE on daemon side

src/Common.cpp, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MessageProtocol/MessageProtocolBLE.cpp, src/ParseDomain.h, src/WSServerCon.cpp, src/WSServerCon.h
- Setting the **mooltipass_status** to **Unlocked** for BLE to be able to connect to the browser extension.
- Temporary solution, until mooltipass_status message is not implemented for BLE.
- It is possible to store and get credential from browser
- Currently only possible to use with one login per service. (Handling multiple login haven't been implemented on fw yet)
- From GUI you can save credentials on Credentials tab
- MMM has not been implemented yet
- _WSServerCon.cpp diff looks messed up, but I only moved device dependent parts of **processMessage** to **processMessageBLE** and **processMessageMini**_
=> Implementing storing/getting credential for BLE from browser and GUI

src/HaveIBeenPwned.cpp, src/HaveIBeenPwned.h, src/MPDeviceBleImpl.cpp, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp, src/WSServerCon.h
In #434 @raoulh mentioned translation is not working in daemon, but I used tr("") before for hibp integration too. I moved the "this password has been compromised %1 times." text to the GUI (WSClient.h) For this a few changes were required regarding emitting hibp check result.
Also there was two translation text in MPDeviceBleImpl.cpp. It is used for progress information and as I checked in MPDevice.cpp translation has not been used for progress messages. (e.g.: "Loading Favorites...", "Favorite %1 loaded").
=> Move string translation to gui from daemon

src/MPDevice_linux.cpp, src/MPDevice_linux.h
Removing EVIOCGRAB according to comments in #434.
=> Remove EVIOCGRAB from MPDevice_linux

src/MPDevice.cpp, src/MessageProtocol/MessageProtocolBLE.cpp, src/WSServerCon.cpp
The `MPCmd::GET_RANDOM_NUMBER` command was already mapped to BLE message **0x0008: Get 32 Random Bytes**.
Moved `get_random_message` processing to use the same for Mini and BLE.
=> Connecting get random number message for BLE

src/Mooltipass/MPNode.cpp
There was an error in MPNode during implementing **EnterMMM** for BLE and accidentally overwrote replace size in `MPNode::setLoginChildNodeData` function which caused error during db export.
=> Fix export db error

src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
Only the first packet's flipbit was set previously, which caused an error if there are multiple packet to send in a message. (e.g.: CMD_DBG_DATAFLASH_WRITE_256B during upload bundle)
=> Fix setting flipbit, when multiple packet to send in a message

src/MPDevice.cpp, src/MPDevice.h, src/MPDevice_win.cpp
During connecting the device there was an issue a few time (around 1 in 30) when CreateFileA returned an Invalid handle for this I implemented a retry logic for deviceOpen and handled the timers as well.
=> Add retry logic for deviceOpen on Windows

src/CredentialsManagement.cpp, src/CredentialsManagement.h, src/CredentialsManagement.ui, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui, src/MessageProtocol/MessageProtocolBLE.cpp, src/MooltipassCmds.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp, src/WSServerCon.h
- Implement 0x0012: Check Credential message
- Added a check before adding a new credential from MC
- Implement Get/Set User Categories (0x0014/0x0015):
- Only displaying on Credentials tab, when Advanced Mode is enabled and BLE device is connected:
- Implement 0x0013: Get User Settings
- Only displayed for BLE device
- Read only, polling with status message
=> [BLE] Implement set user categories, add User Security Settings

src/CredentialsManagement.cpp, src/CredentialsManagement.h
When a previous card/device with credentials entered MMM, then if we switch to an empty device the last card's credential is displayed in MMM:
If the previous device was disconnacted in MMM, then the credential tree view remained also.
In the fix I cleared every MMM ui element before entering.
=> Clear MMM UI before entering

src/SystemNotifications/SystemNotificationWindows.cpp, src/SystemNotifications/SystemNotificationWindows.h
Previously `NOC_GLOBAL_SETTING_TOASTS_ENABLED` registry entry was checked, but since Focus Assist was introduced with Win10 1803 update it is not working.
Since then `ToastEnabled` regentry is used for detecting it. (_HKEY_CURRENT_USER\Software\Microsoft\Windows\CurrentVersion\PushNotifications_) 
Implemented checking both entry to support previous Win10 too.
=> #360 Detect Win10 Focust Assist enabled for checking do not disturb

src/MPDevice_win.cpp
Resize is only extending the size of the QByteArray without initializing them, so changed to insert zeros to fill the message.
=> Writing zeros instead of random bytes to device on Windows

src/MPDevice.cpp, src/MPDevice.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MessageProtocol/MessageProtocolBLE.cpp
Daemon can process debug messages received from BLE device.
E.g.:
=> Map Debug Message for BLE and implement printing it

src/AppGui.cpp
Workaround for the following Qt issue: https://bugreports.qt.io/browse/QTBUG-68850
Most elements were invisible in MacOS Mojave, when Dark mode is activated.
=> Fix MacOS Mojave Dark mode display issue

src/MPDevice.h, src/MPDevice_emul.cpp, src/MPDevice_emul.h
Emulation mode was crashing after the Device Settings refactor, because of the missing init calls.
=> Fix emulation mode

src/MPDevice.cpp, src/MPDevice.h, src/Mooltipass/MPNode.cpp, src/WSServerCon.cpp
- Move export_database and import_database to the common part of WSServerCon' processMessage function
- Change left MP_NODE_SIZE for the correct size in MPNode
- Add an extra flag to exported file for BLE
- Set correct Node types
=> Implement credentials import, export for BLE

src/MPDevice.cpp, src/MPDevice.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp
- Persist user category names and isBle information in the exported payload
- Loading user category names during import if available
- Changed magic number in import functions
=> Persist user category names during export/import

src/MainWindow.cpp, src/MainWindow.ui, src/Settings/DeviceSettings.cpp, src/Settings/DeviceSettings.h, src/Settings/DeviceSettingsMini.cpp, src/Settings/DeviceSettingsMini.h, src/Settings/ISettingsGui.h, src/Settings/SettingsGuiBLE.cpp, src/Settings/SettingsGuiMini.cpp
File management and integrity check is hidden.
The following device settings are implemented for BLE so far:
=> [BLE] Only display implemented features for BLE

src/Settings/SettingsGuiBLE.cpp
#484
Also hide BLE Reserved device setting as it has no functionality so far.
=> [BLE] Hide BLE Reserved Device Setting too

src/LoginItem.cpp
Remained during #482, causing invalid json size for Mini.
=> Remove category from LoginItem JsonObject for Mini

src/Common.h, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
Implemented the workaround @limpkin mentioned in #487:
> 
> 
> strategy to be implemented on moolticute's side: whenever multiple packets are expected, if another packet isn't received withing 2 seconds, reset moolticute comms
I added a 2 sec timer when based on the first received packet multiple packets are expected.
If the timer expires it removes the actual command from the queue and returns the job with failure, after that the command processing is continuing.
I was not able to test it, because I have never experienced a reset. So I tested with adding random sleeps for longer messages and it fixed the communication when the timer expired.
=> #487 Handle when reset occurs

src/MPDevice.cpp, src/MPDevice.h
Originally with the `QTimer::singleShot` delay, it was not guaranteed the init messages are called first, because during the 100 msec delay it was possible the GUI is requesting some data (e.g.: user category, language/layout related commands) and those were sent earlier causing a stuck in communication.
So I added a `TimerJob` first with a higher (300 msec) timeout, so there won't be any job added to the commandqueue before the init messages. However reset flip bit is written directly to the device without using the commandqueue, hence for reset flip bit a lower delay (150 msec) is still necessary.
=> Make sure init messages are called first with a TimerJob

src/MPDevice_win.cpp, src/MPDevice_win.h
Analysed in https://github.com/mooltipass/moolticute/issues/486#issuecomment-557839802.
https://docs.microsoft.com/en-us/windows/win32/api/fileapi/nf-fileapi-writefile#parameters
> lpBuffer
> 
> A pointer to the buffer containing the data to be written to the file or device.
> 
> **This buffer must remain valid for the duration of the write operation.** The caller must not use this buffer until the write operation is completed.
char* buffer was used from local variable `QByteArray ba`, but it is possible the write operation is not finished by the execution returns from `MPDevice_win::platformWriteToDevice` and in that case write operation is using a pointer to a deallocated buffer, which we can see in the #486 attached logs.
Copying the buffer into a new char* and deleting it when the …
=> #486 Fix winapi WriteFile buffer deallocation issue

src/MainWindow.cpp, src/MainWindow.ui
=> #512 Enlarge keyboard layout comboboxes for BLE

src/AppGui.cpp
Implemented a workaround, wrote an analysis here:
https://github.com/mooltipass/moolticute/issues/479#issuecomment-546713609
Fix for #508 too.
=> #479 Workaround for Mac systray menu disabled issue

src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
When there is no bundle on the device 0xFFFF (65536) returned from the device for `0x0019: Get Number of Languages` and `0x001A: Get Number of Keyboard Layouts` messages.
=> [BLE] Handle invalid number of layout and language sent

src/MPDevice_mac.cpp
After Aux MCU Flash a cancel user request message is written directly to the device:
https://github.com/mooltipass/moolticute/blob/master/src/MPDevice.cpp#L162
This one is called from setupMessageProtocol, which was called before initializing the QThreadPool.
=> [BLE] Fix Aux MCU Flash crash on Mac

src/MPDevice.cpp
- DEV_DEBUG macro was not changed
- Double EmptyAddress check for temp_pnode_address
=> [BLE] Minor favorite related changes

src/WSServerCon.cpp
When `ping` is received the following line was printed:
`DEBUG: (2019-12-03T19:25:06.301) WSServerCon.cpp:1165 - QJsonValue(null)  message have not implemented yet for BLE`
Because msg field is `Null` for ping message.
Also ping is not processed at all so I can return after the check.
=> [BLE] Handle when ping is received

src/MainWindow.cpp, src/MainWindow.h, src/Settings/SettingsGuiBLE.cpp
Removed the check where requestBleKeyboardLayout was only sent when the layout combobox is empty.
Also made sure `requestBleKeyboardLayout` only sent once on device connection.
=> [BLE] Fetch keyboard layout and language after every BLE device connection #500

src/MainWindow.ui, src/MooltipassCmds.h, src/Settings/DeviceSettingsBLE.cpp, src/Settings/DeviceSettingsBLE.h, src/Settings/SettingsGuiHelper.cpp
Added new "Device lock on USB disconnect" device setting to BLE's General Settings section:
=> [BLE] Add device setting "Device lock on USB disconnect"

src/MPDevice.h, src/MainWindow.cpp, src/MainWindow.h, src/Settings/SettingsGuiBLE.cpp, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp
- #552 fixed: fetching parameters, when user is logged in
- Only display Current User Language, Bluetooth Keyboard Layout and USB Keyboard Layout, when user is logged in
- Implemented a cache mechanism for layout and language and only update the lists when a different is received
=> [BLE] Keyboard layout and languages related fixes

src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MainWindow.ui, src/Mooltipass/MPSettingsBLE.cpp, src/Mooltipass/MPSettingsMini.cpp, src/Settings/DeviceSettings.cpp, src/Settings/DeviceSettings.h, src/Settings/DeviceSettingsBLE.cpp, src/Settings/DeviceSettingsBLE.h, src/Settings/DeviceSettingsMini.cpp, src/Settings/DeviceSettingsMini.h, src/Settings/SettingsGuiBLE.cpp, src/Settings/SettingsGuiHelper.cpp, src/Settings/SettingsGuiHelper.h, src/Settings/SettingsGuiMini.cpp
- Added Knock detection settings like for Mini
- Renamed credential prompt user setting to Knock Detection Disabled
=> [BLE] Add Knock detection setting #551

src/WSServerCon.cpp
On startup device memory is not received from the device when sendVersion is called.
Calling sendVersion when flashMbSize is set fixes the issue.
=> [BLE] #522 Send device related informations to GUI on flashMbSize change too

src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
Fix for #556 
Bundle file was only opened after erasing flash. If opening was not successfull device remained in incorrect state.
=> [BLE] Check if bundle file is readable at the start of the upload bundle process

src/CredentialModel.cpp
Fix for #553 
When the user entered a new credential from MMM and there was a previous credential with the same substring it found the previous first and inserted an empty row to the grid.
E.g.:
We have a credential with **'aaa'** service name and entering a new one with **'aa'**, then an empty line is inserted for 'aaa' services:
https://doc.qt.io/qt-5/qabstractitemmodel.html#match
`The search begins from the start index, and continues until the number of matching data items equals hits, the search reaches the last row, or the search reaches start again - depending on whether MatchWrap is specified in flags. If you want to search for all matching items, use hits = -1.`
The default value for the flags is **Qt::MatchFlags(Qt::MatchStartsWith|Qt::MatchWrap)** and because of hits is 1 after …
=> #553 Fix empty row inserted in the grid on credential added from MMM

src/CredentialsManagement.cpp, src/CredentialsManagement.h, src/PasswordLineEdit.cpp, src/PasswordLineEdit.h
PasswordLineEdits was limited to 31 characters, set this to 64 chars, when BLE is connected.
Also enabled to generate 64 long passwords.
=> [BLE] Enable MMM password inputs to accept 64 characters

src/CredentialModel.cpp
fix for #541
Category was uninitialized in this case, which caused the issue, because in release build it was some garbage value.
=> [BLE] Set default category value, when service is already exist

src/MPDevice.cpp, src/MPDevice.h
Handle the fw changes mentioned in #562.
For BLE only sending a status message request on connection after that the device is sending a status message after every change, which is handled on daemon side.
=> [BLE] Handle the new status message on daemon side

src/AppGui.cpp, src/AppGui.h
There were some cases where warning notifications only sent once.
Possible fix for #496
=> Reset status for warning notification, when device status or connection is changed

src/MPDevice.cpp, src/MPDevice.h
With this timer singleshot, when MPDevice destructed before the delay, then the function is not called.
=> [BLE] Fix resetflip crash, when device disconnected right after connection

src/MPDevice_linux.cpp, src/MPDevice_linux.h, src/UsbMonitor_linux.cpp
Fix for #594
According to @bitgestalt https://github.com/mooltipass/moolticute/issues/594#issuecomment-589958735, removing unused `sockNotifWrite`.
It was only used for libusb implementation before #428 .
Also removed `setEnabled(true)` calls for the sockets. 
https://doc.qt.io/qt-5/qsocketnotifier.html#details
> The socket notifier is enabled by default...
=> Remove unused sockNotifWrite from Linux MPDevice

src/CredentialsManagement.cpp, src/MPDevice.cpp, src/MPDevice.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
Fix for #605
Issues fixed:
- Fetch categories when smart card is inserted and unlocked
- During import move set categories after MMM is started
- Set categories is not prompted in this case
- Fetch categories in daemon if it was not requested from Gui
=> [BLE] Fix category related issues

src/Common.cpp, src/Common.h
Qt::ISODateWithMs enum value was only added in Qt5.8
It is used for the timestamp in logging.
https://doc.qt.io/archives/qt-5.11/qdatetime.html#toString-1
> use the format Qt::ISODateWithMs, which corresponds to yyyy-MM-ddTHH:mm:ss.zzz
=> Fix backward compatibility issue with Qt5.5.1 for Xenial build

src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
Move https://github.com/mooltipass/moolticute/pull/608/commits/20a807b27b04abb0d7027dc280294d831a23b253#diff-e9a41bdf95cd0a995d2c81602f7c5c00R120 after the first status message arrived and we know that the device is unlocked.
=> [BLE] Only fetch categories on daemon side when device is unlocked

src/MainWindow.cpp
Implemented #606
After db export:
=> Display confirmation message for database export

data/moolticute.sh
Using pkexec to authenticate superuser for installing udev rules based on @kaorihinata suggestion in https://github.com/mooltipass/moolticute/issues/506#issuecomment-556196028
=> #506 Fix silent udev rules install

data/moolticute.sh
Removed udev rules versioning based on https://github.com/mooltipass/moolticute/issues/506#issuecomment-596763166.
=> Copy and reload udev rules if changed

src/CredentialModel.cpp, src/CredentialsManagement.cpp, src/LoginItem.cpp, src/LoginItem.h, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/Mooltipass/MPNode.cpp, src/Mooltipass/MPNodeBLE.cpp, src/Mooltipass/MPNodeBLE.h, src/PasswordLineEdit.cpp, src/PasswordLineEdit.h, src/TreeItem.cpp, src/TreeItem.h
Implemented #621.
When `MMM Stor. Conf.` is enabled and credential is saved from MMM, but the prompt is not accepted, then a blank password is saved. After entering MMM again a **"Non-initialized password"** is shown for the credential's password field:
=> [BLE] #621 Non-initialized password support

src/CredentialModel.cpp
When we are saving credentials in MMM, it tries to update the currently selected credential. However when the password was changed, but it is locked, then new password was not saved.
Fixed it with an extra check for empty password, which only can happen, when the password field is locked.
=> #629 Fix not saved password in MMM

src/AppGui.cpp, src/Common.cpp, src/Common.h, src/DbBackupsTrackerController.cpp, src/MPDevice.cpp, src/MPDevice.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MessageProtocol/IMessageProtocol.h, src/MessageProtocol/MessageProtocolBLE.cpp, src/MessageProtocol/MessageProtocolBLE.h, src/MessageProtocol/MessageProtocolMini.h
**Extra user datas are added to export file:**
- HID_CMD_GET_CPZ_LUT_ENTRY
- user security settings
- user language
- bt keyboard layout
- usb keyboard layout
They are imported, when an initailized card inserted.
**Fix for the SimpleCrypt bug** is also implemented.
=> [BLE] Add user datas for database import feature

src/MPManager.cpp
Only check for other MP device during usb removal, when an MP was removed and no other MP is connected.
=> Fix device disconnecting issue, when other HID device removed

src/MPDevice.cpp
When user is trying to import a ble backup file to the mini:
=> Prevent ble backup file import into the standard mini

src/MainWindow.cpp
For BLE "MMM Mode" status was introduced and when it is set during entering MMM `updatePage` is called, which removed the waiting screen.
=> [BLE] Fix waiting screen for entering MMM

src/MPDevice.cpp, src/MPDevice.h, src/MPDevice_win.cpp
**Issue:**
When device is not opened on the first try MC tries to open it 50 msec later. In the meantime it is possible a command is getting in the queue which will get before reset flipbit command and causing communication freeze.
**Fix:**
After open device retry we clear the command queue to ensure reset flipbit is the first message to write.
=> [BLE] Reset communication, when device opened after retry to avoid communication freeze

src/MPDevice.cpp
Only send ENTER_MMM message during import for non BLE device. Fix for #701
=> [BLE] #701 No need to send enter MMM during importing an unknown card

src/MPDevice_mac.cpp, src/MPManager.cpp, src/MPManager.h, src/UsbMonitor_mac.cpp, src/UsbMonitor_mac.h
Fixed #702 on Windows, Mac and Linux, but could not test on Linux, because was not able to connect BLE with BT.
On Mac when device is connected with BT, then plug in USB disconnecting BT device and connecting USB device caused crash, because the reported callback still received messages and crashed MC. For this I unregistered the Report Callback and closed the device in MPDevice_mac destructor.
=> [BLE] #702 Keep looking for USB devices when connected through Bluetooth

src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/Settings/DeviceSettings.h, src/Settings/SettingsGuiBLE.cpp, src/Settings/SettingsGuiBLE.h, src/Settings/SettingsGuiHelper.cpp, src/Settings/SettingsGuiMini.cpp, src/Settings/SettingsGuiMini.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp
Previously languages and layouts was only fetched when a different device was connected (e.g.: BLE after a Mini). 
Fixed it and now also fetched when the number of languages or layouts is different as before.
`onlyCheck` is needed to force fetching when different devices connected.
=> [BLE] Check number of languages/layouts on connection and fetch if different as the last

src/MPDevice.cpp
Fix issue introduced with #703, where during standard import entering mmm was skipped also.
=> [BLE] Only skip enter MMM for import, when an unknown card is inserted to BLE

src/MPDevice.cpp, src/MPDevice.h, src/MacSystemEvents.mm, src/MainWindow.cpp, src/MainWindow.h, src/MessageProtocol/MessageProtocolBLE.cpp, src/MooltipassCmds.h, src/SystemEvent.h, src/SystemEventHandler.cpp, src/SystemEventHandler.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp
Implement sending locked/unlocked messages when computer is locked/unlocked. #711
Also send current computer status when device is connected.
Storing computer state in MC (MainWindow) and handling lock/unlock on every OS.
=> [BLE] #711 Inform device about computer is locked/unlocked

src/MainWindow.cpp
Fix for #723.
Device settings are fetched every time, but it is cached on Gui side, so need to reset it on device disconnections.
=> #723 Reset device settings on device disconnection

src/MainWindow.cpp, src/MainWindow.ui, src/Mooltipass/MPSettingsBLE.cpp, src/MooltipassCmds.h, src/Settings/DeviceSettingsBLE.cpp, src/Settings/DeviceSettingsBLE.h, src/Settings/SettingsGuiBLE.cpp, src/Settings/SettingsGuiHelper.cpp, src/Settings/SettingsGuiMini.cpp
New Settings:
- SETTINGS_DISABLE_BLE_ON_CARD_REMOVE
- SETTINGS_DISABLE_BLE_ON_LOCK
- SETTINGS_NB_20MINS_TICKS_FOR_LOCK
- SETTINGS_SWITCH_OFF_AFTER_USB_DISC
New settings from image: 
- Inactivity Timer
- Switch off device after USB Disconnection
- Disable BLE on card removed
- Disable BLE on device lock
=> [BLE] Add new device settings on MC side

src/Settings/SettingsGuiHelper.cpp
After #738 it was possible `resetSettings` called before `m_settings` is initialized, which was causing a GUI crash. (e.g.: without a device connected start daemon first, than gui and in some cases mp_disconnected sent too early)
Handled with adding a null check in `resetSettings`.
=> Add null check for settings in resetSettings

src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/WSServerCon.cpp, src/WSServerCon.h
1. Need to `sendVersion` before `mp_connected` message for GUI (otherwise in onDeviceConnected function the previous device is used)
2. After reconnection sometimes user categories were cleared, so sending it when it is empty on daemon side.
=> Fix device disconnection/reconnection issues

src/CredentialsManagement.cpp, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/TOTPCredential.cpp, src/TOTPCredential.h
**Base32 validation**
Only the valid character check was implemented for Base32 string, but it was still possible to enter an invalid one, now created an extra check for that and if the user enters an invalid one, displaying the following dialog:
Base32 regular expression:
`"^(?:[A-Z2-7]{8})*(?:[A-Z2-7]{2}={0,6}|[A-Z2-7]{4}={0,4}|[A-Z2-7]{5}={0,3}|[A-Z2-7]{7}={0,1})?$"`
**Clearing TOTP Credential during MMM exit**
The previous implementation of clear was not called if there were no other credential related modification, so TOTP credentials were  saved again during the next MMM enter/exits.
=> [BLE] Fix clearing TOTP Credential during MMM exit & validate secretkey string

src/MainWindow.cpp
Fix for #737 
It was implemented in the code, but later in the function enabled all tab again.
=> #737 Disable Tabs when entering Credentials or Files management mode

src/MainWindow.cpp, src/MainWindow.ui
=> [BLE] Fix Management Storage Confirmation Prompt User Settings

src/Common.h
https://doc.qt.io/qt-5/qtendian.html#qToLittleEndian
`Note: Since Qt 5.7, the type of the dest parameter is a void pointer.`
For xenial QT version 5.5.1 is used.
=> Fix xenial build issue, add qToLittleEndian(T,void*) for QT version bellow 5.7

src/FilesManagement.cpp, src/FilesManagement.ui, src/MPDevice.cpp
When file is selected for export, first fetch the selected file:
And only after that display the save dialog:
=> Fetch files before displaying save dialog for Files Management export

src/CredentialModel.cpp, src/CredentialModel.h
Fix for #690 
Previously when the user changed a credential's category which was set as favorite then favorite was reset.
Currently the following logic is implemented during category change:
- If favorite is available for the new category, then using it
- If the same favorite is taken in the new category then search for an available slot
- If no available favorite slot for the new category then reset favorite for the credential
=> [BLE] #690 Fix category change of favorite credentials in MMM

src/CyoEncode/Base32.cpp, src/MPDeviceBleImpl.cpp
With the original `decodedArr.append((char*)&decoded.front());` processing sometimes extra bytes were appended to the buffer.
Implemented processing the decoded vector and truncating the ending zero bytes.
=> [BLE] Fix Base32 decode result processing for TOTP

src/CredentialsManagement.cpp
Fix for #688.
If category is changed until it is not confirmed or discarded disable favorite change.
=> [BLE] Disable favorite selection on category change in MMM

src/BleDev.cpp, src/BleDev.ui, src/CyoEncode/Base32.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MessageProtocol/MessageProtocolBLE.cpp, src/MooltipassCmds.h, src/WSServerCon.cpp
- Enlarged Upload Password field
- Handle upload passwords correctly
- Changed upload message to the new ones
- Changed QByteArray back calls to `size() - 1` for Qt backward compatibility
=> [BLE] Migrating upload technique to the new messages

src/MainWindow.cpp
Previously Bundle Version text was displayed for the original mini too:
With this fix it is removed.
=> Do not display Bundle Version text for Mini on About tab

src/AsyncJobs.h, src/Common.cpp, src/Common.h, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp
When there is no bundle on the device: 
- Filter and only accept allowed messages in this case.
- Display BleDev tab for uploading bundle and disable other tabs:
- Drop messages, when no bundle status received
- For BLE ensured the first message is a status request
=> [BLE] Handle NoBundle status on device

src/MPDevice_linux.cpp, src/MPDevice_linux.h
With bluetooth we receive an extra byte at the beginning during read, so need to increase the buffer size by 1 to read the entire packet.
=> [BLE] Fix buffer size, when BLE is connected with bluetooth

mac/Info.plist
Temporarily disable dark mode in moolticute till it's officially supported to prevent inputs from going dark.
(https://developer.apple.com/documentation/appkit/nsappearancecustomization/choosing_a_specific_appearance_for_your_macos_app)
=> Disable dark mode till it's supported

src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
When device was locked fetch data nodes response's size was 1 which was causing an infinite loop with fetching.
Moved fetch data files from device connection to unlocked status message arrival.
Also handled when `FETCH_DATA_NODES (0x0031)` response has an invalid size.
=> [BLE] Only fetch data files, when device is unlocked

src/DbBackupsTrackerController.cpp, src/DbBackupsTrackerController.h
Fix for #809 
Signals and slots for `DbBackupsTrackerController` was connected multiple time, because of fwVersion changes (from NONE to actual firmware fetched), which caused the dialog appears multiple times.
With the fix I ensured it appears only once.
=> [BLE] Display Database Backup Monitor more recent dialog only once

src/DbBackupsTrackerController.cpp, src/PromptWidget.cpp, src/PromptWidget.h
Previously we had a fix in #733 for an other prompt ("You haven't made a backup of your database in a while. "), with this PR "Credentials on the device are more recent. " prompt will not display in MMM as well.
=> Do not display more recent backup prompt in MMM, fix #816

src/MPDevice.cpp
The original problem that during deleting fido nodes `checkLoadedNodes` was checking dataNodes as well, which would not cause an issue, but previously startNodes/startDataNodes were not cleared after exiting MMM.
So when database was exported or Files Credentials entered before deleting Fido Credential then the checkLoadedNodes returned false because there is the previously used startDataNode, but dataNodes are not fetched for Fido Credentials.
=> [BLE] Fix Fido credential deletion issue, when data nodes were fetched earlier

src/FidoManagement.cpp, src/FidoManagement.h
fix for #821
Only when a fido credential is selected display Delete button, else hide it:
=> [BLE] Fix Fido credential delete crash when website is selected fix #821

src/DbBackupsTracker.cpp, src/DbBackupsTracker.h, src/DbBackupsTrackerController.cpp, src/DbBackupsTrackerController.h, src/MPDevice.cpp, src/WSClient.cpp, src/WSClient.h
There were 3 issues with export prompt:
Issue:
After Fix:
After saving a file outside of MMM a case was not handled for BLE and every time dataChangeNumber was set to 0, so import dialog was displayed.
Fix:
Displaying export prompt right after file/credential saved.
=> [BLE] Fix export prompt errors, fix #813

src/MainWindow.cpp
Previously Lock Unlock Features was not reset to the original values if No Password Input Prompt was enabled:
In this case for the values a bitmask is applied and when I disconnected BLE and connected an original Mini then Lock Unlock Feature was not working correctly because of the values from BLE.
=> Set Lock Unlock Feature values to originals after BLE device disconnection

src/Common.cpp, src/Common.h, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui, src/MessageProtocol/MessageProtocolBLE.cpp, src/Mooltipass/MPSettingsBLE.cpp, src/MooltipassCmds.h, src/Settings/SettingsGuiBLE.cpp, src/Settings/SettingsGuiBLE.h, src/Settings/SettingsGuiHelper.cpp, src/Settings/SettingsGuiHelper.h, src/WSClient.cpp, src/WSClient.h
Added "Enforce at connection" checkbox for keyboard layouts:
If they are enabled then after user login when layouts are fetched sending the new 0x0037 message to enforce the layout.
=> [BLE] Add enforce keyboard layout option, fix #807

src/Common.cpp, src/Common.h, src/MPDevice.cpp, src/MPDevice.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MainWindow.h, src/Mooltipass/MPMiniToBleNodeConverter.cpp, src/Mooltipass/MPMiniToBleNodeConverter.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp, src/WSServerCon.h
Import and converting mini data nodes to BLE data nodes.
Special retrieve of mini files are implemented as well.
Only import files from mini backup, if the bundle >=1 otherwise display a warning information for the user during importing:
=> [BLE] Implement import files from mini backup

scripts/ci/linux/after_success.sh
This patch triggers a build on OBS after a linux build has completed and if the current git commit is equal to the most recent tag, same as for the logic publishing a git release.
This patch requires the following environment variables to be set in the travis environment:
- OBS_API, for now "https://api.opensuse.org"
- OBS_PROJ, for now "home:fawz:mooltipass"
- OBS_USER, the user to authenticate as against the OBS_API
- OBS_PASS, the user's password
=> (remote-control-OBS) trigger OBS build after a successful linux build

src/MPDevice.cpp, src/MessageProtocol/MessageProtocolMini.h
Until now 63 and 64 characters long logins and passwords were rejected during CSV import.
=> [BLE] Accept 64 chars long login and password from CSV import, fix #839

src/NotesManagement.cpp
It was changed in #850, but realized it is causing backward compatibility issue with older Qt versions, because they does not contain the new function for pixmap.
=> Use QLabel pixmap by const ptr for backward compatibility

Makefile, data/moolticute.metainfo.xml
This adds support for software centers. [More information](https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html#sect-Quickstart-DesktopApps). 
If moolticute is available in a distribution's repository, the metainfo makes sure users can find it within their software centers (gnome-software, discover, ...). This is useful if they are not familiar with command line tools.
A lot more information could be added. For example screenshots (they need to be available on a url). [Gajim](https://dev.gajim.org/gajim/gajim/-/blob/master/data/org.gajim.Gajim.appdata.xml.in) is a good example which uses a lot of the features.
=> Add AppStream metainfo file

README.md
Fedora 33 and > uses `qt5-qtbase` rather than `qt5` for the qt5 base package.
I wasn't sure the best way to change the README.md file while still making it copy-and-pastable, so I just added the updated
string in a new code fence.
=> Added additional fedora dnf intall command.

src/AsyncJobs.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/WSServerCon.cpp, src/WSServerCon.h
Nihm recondition takes more than 4 hours, during that time a messages arrive to daemon (mostly get random numbers) and waits for recondition finish.
On Windows when we send recondition response message to the gui for some reason instead of the other messages sending the same one for recondition every time. (Thats why multiple dialog was displayed)
I added a custom job for sending the result, which resolved the problem.
=> [BLE] Fix multiple popups on recondition finish, fix #880

src/MPDevice.cpp
QByteArray [compare](https://doc.qt.io/qt-5/qbytearray.html#compare-1) function is only introducted in Qt 5.12, using [== operator](https://doc.qt.io/qt-5/qbytearray.html#operator-eq-eq) instead of that.
In PR #892 it was mentioned "`for the 1M / 2M / 32M version it is 0100`", implemented here.
=> [BLE] Integrity Check fix backward compatibility issue and getMemoryFirstNodeAddress

src/BleDev.cpp, src/BleDev.h, src/DeviceDetector.h, src/MainWindow.cpp, src/MainWindow.h
It was not enough to handle keyPressed/Released only in BleDev widget, because if I simple change to BleDev tab from another tab, until a UI element is selected MainWindow is catching the key events.
=> [BLE] Bypass battery check for bundle upload if ctrl is pressed

src/CredentialsManagement.cpp, src/CredentialsManagement.ui, src/MainWindow.ui
Discard credential changes:
Discard all changes:
Also fix for #899, but I was not able to test it, because "Please Approve Request On Device" text were never cut off for me.
=> Fix credential management button sizes, fix #889

gui.pro, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui, src/TutorialWidget.cpp, src/TutorialWidget.h
Implemented a tutorial for Moolticute which is going through all the tabs for a newly installed MC. (based on setting config)
Only displayed for BLE.
=> [BLE] Add tutorial for Moolticute

src/MainWindow.cpp
Minor text modification on the system notification to improve clarity about exactly what device is low on battery, for operating systems and desktop environments that don't readily indicate what application has generated a notification.
Closes #959.
=> Improved clarity of low battery system notification.

src/MPDeviceBleImpl.cpp
When get credential prompt for fallback service was denied the callback was called with true value too, which caused the crash later during it tried to retrieve the credential from empty response array.
=> [BLE] Fix fallback service get credential crash

src/Common.cpp, src/Common.h, src/CredentialsManagement.cpp, src/MPDeviceBleImpl.cpp, src/MainWindow.cpp, src/WSClient.cpp, src/WSClient.h
Display the correct error message when confirmation prompt denied during exit MMM after a password change:
Fix #971.
=> Fix exit MMM error message, fix #971

src/BleDev.cpp, src/BleDev.h, src/BleDev.ui, src/Common.h
Check password, serial number, bundle version from filename.
For 3 special filename start the update with the default password.
Implemented #973
=> [BLE] Update firmware with password from filename, fix #973

README.md
This should give a guideline to follow on how to install setup moolticute on standard linux marchine
https://github.com/mooltipass/moolticute/issues/975
=> Improve documentation for standard linux user

src/AppGui.cpp
On some Gnome on Wayland platforms, moolticute wouldn't launch with a
protocol error: "Invalid min/max size". This seems to be caused by an
invalid maximum width value. This patch resets this value.
Fixes #872
=> Fix Gnome on Wayland crash

src/CredentialsManagement.cpp, src/CredentialsManagement.ui, src/MainWindow.cpp, src/MainWindow.ui
Put Moolticute settings tab content to a scroll area:
Removed section texts for Credential tabs:
With these changes MC's min height with banner on the bottom is 700px.
=> Decrease minimum height of Moolticute

src/CredentialsManagement.cpp
When in MMM a filter was applied and a service name were changed it disappeared from the treeview. The name change procedure tried to update credentials information on the right side, which caused the crash due to invalid ModelIndex.
**Fix**: Remove filter if new service name does not contain filter text.
=> Fix crash during service name change, fix #984

src/MainWindow.cpp
On Mac we only need to push SHIFT+F1/F2/F3 for secret tabs.
=> Simpler key combination for secret tabs on Mac, fix #979

src/CredentialsManagement.cpp, src/DbBackupsTrackerController.cpp, src/LoginItem.h
During removing credential in MMM "Discard Modification" dialog was displayed due to an issue introduced with #996
=> Fix delete credential in MMM issue

src/CredentialsManagement.cpp
When I remove a credential then "Discard all changes" and "Save all changes" displayed on the bottom, I choose an other credential and e.g. add a description. Now "Discard Changes" and "Confirm changes" is displayed for the credential.
If select "Save all changes" the not confirmed description will be also saved.
With this fix the not confirmed changes are not saved.
Also enable add credential fields on the top when exiting MMM during a credential edit.
=> Do not save not confirmed changes when exiting MMM

.github/ISSUE_TEMPLATE/10-bug_report.md, .github/ISSUE_TEMPLATE/20-feature_request.md
No need to have a combined issue templates, define one template for bug reports and another for feature requests.
=> Refactor common issue template to separate issue templates

src/Common.h, src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MainWindow.cpp, src/MainWindow.h
Device is connected and unlocked then MC was started and notes were not fetched.
**Issue**: During starting MC gui is started first, which is starting the daemon process. When gui is detecting the connected BLE it is sending a notes request to daemon, but at this moment bundle version and status have not been fetched from the device on daemon side, hence notes were not fetched.
**Fix**: Only send the fetch request from GUI, when bundle version fetched and status is Unlocked.
=> [BLE] Fix notes fetch condition, fix #1020

src/MainWindow.cpp, src/MainWindow.ui
Remove option to customize cmd + Q for terminate application. Now it will only minimize Moolticute.
=> Minimize MC with cmd + Q on Mac

src/CredentialsManagement.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui, src/MessageProtocol/MessageProtocolBLE.cpp, src/MooltipassCmds.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp
- If a category is selected setting it as current category, when BLE device is connected and unlocked.
- Using category names from connected BLE device's categories.
=> [BLE] Add Current Category setting

src/QtAwesome/LICENSE.md
`src/QtAwesome/QtAwesome/fonts/fontawesome-4.6.1.ttf` is licensed under SIL OFL 1.1.
This license is missing from the repository, but should be included.
I was notified about the license missing from the Fedora package. Since this should be included in the tarball anyway, I've added it.
=> Add SIL OFL 1.1 license

src/MPDeviceBleImpl.cpp
Behavior changed between Qt5 and Qt6, QString(QByteArray) constructor is not cutting the zero bytes anymore, need to handle it.
https://bugreports.qt.io/browse/QTBUG-97451
=> [BLE] Remove zero bytes from end of BLE name setting

src/Mooltipass/MPNode.cpp, src/Mooltipass/MPNode.h, src/Mooltipass/MPNodeBLE.cpp, src/Mooltipass/MPNodeBLE.h, src/Mooltipass/MPNodeMini.cpp, src/Mooltipass/MPNodeMini.h
For parent node "last child node used addr" and for child node "pointed to child address" was included.
=> [BLE] Fix get/setLoginParent/ChildNodeData

src/Common.cpp, src/Common.h, src/MPDevice.cpp, src/MPDevice.h, src/Mooltipass/MPNodeBLE.cpp, src/Mooltipass/MPNodeBLE.h
Check the addresses from the imported DB and find the correct service/login for them in the device's DB.
=> [BLE] Add last used child node and pointed to address check for import

src/NotesManagement.ui
Using the _courier_ font in the Notes editor.
The notesmanagement.ui file was changed in the QT designer instead of a text editor, which generated a _height_ change and increment of the _stackedWidget_ _number_.
Tested in WIndows 10 only.
=> Issue #953 Monospaced notes

src/MessageProtocol/MessageProtocolBLE.h
Credentials with TOTP datas contains one extra json element, but this size was not updated with the credential package size.
=> [BLE] Update TOTP package size

src/Common.h, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui, src/MessageProtocol/MessageProtocolBLE.cpp, src/MooltipassCmds.h, src/WSClient.cpp, src/WSClient.h, src/WSServerCon.cpp
For devices with above 2000 serial number compare serial number with platform serial, if they are not equal display error message and option to set the correct serial number.
=> [BLE] Add option to correct serial number

src/MPDevice.cpp, src/MPDeviceBleImpl.cpp, src/MPDeviceBleImpl.h
Fetching notes when change numbers set.
**Other issue fixed**: When deleting note from Files Management we need to fetch notes after exiting.
I am fetching notes after MC exited from MMM, but the new status message have not received at this point, so I needed to enable fetchNotes for MMMMode status too.
=> [BLE] Fetch notes on user change

src/MPDevice.cpp
In Qt6 without telling quint32 explicitly, the size is {0x00,0x00,0x00,0x00} every time and the uploaded data is incorrect.
=> [Mini] Fix files upload for Qt6

src/CredentialsManagement.cpp
There was an isseu when we linked a credential and wanted to add a new one in MMM instead the typed password it used the previous link. This issue is fixed with clearing the linkedAddress after confirming the linking.
Also fixing QueuedConnection issue on Qt6.
=> [BLE] Fix adding new credential after linking

src/CredentialsManagement.cpp, src/CredentialsManagement.h, src/CredentialsManagement.ui, src/MainWindow.cpp, src/PasswordLineEdit.cpp, src/PasswordLineEdit.h
When I wanted to save a credential without password and one of the QLineEdit widget is in the focus then the Save button is enabled even after Alt key is released.
In Qt6 the keyReleaseEvent is not received in CredentialsWidget.
[QLineEdit keyReleaseEvent](https://doc.qt.io/qt-6/qlineedit.html#keyReleaseEvent) was overwritten in Qt6. In Qt5 and before this was handled in event function.
The problem in Qt6 they are not calling keyReleaseEvent's parent function, so the event is not delegated to the parent classes, therefor in CredentialsWidget we are not getting this event.
I created a new subclass (SimpleLineEdit) where I am calling the parent's (QWidget) keyReleaseEvent function from the overwritten one.
I am using this SimpleLineEdit for the adding credentials UIs.
=> [BLE] Fix saving credential without password Qt6

src/AppGui.cpp
Since Qt6 quit is not exiting application properly on Mac, daemon keeps running and prepareToQuit is not called.
=> Fix application exit on Mac

src/CredentialsManagement.cpp, src/CredentialsManagement.h
Issue was mentioned here: https://github.com/mooltipass/moolticute/issues/1100#issuecomment-1381945658
When a private or invalid domain was entered for multiple domains during save these were discarded without any notification.
With this fix I display a dialog, where showing these not saved domains:
=> [BLE] Display when entered multiple domain is invalid

src/MainWindow.cpp, src/MainWindow.h
Only send low battery notification if a valid battery % was received earlier.
I assume BT reconnections caused #1034, this logic would prevent the multiple notifications.
=> [BLE] Fix multiple low battery notification

src/CredentialsManagement.cpp, src/CredentialsManagement.h, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui
fix #1100 
It adds a new config option checkbox and skips TLD validation when setting is enabled.
=> add disable TLD check option

src/MPDevice.cpp
Sending json response after the following commands sent to device:
-inform_lock
-inform_unlock
-lock_device
=> [BLE] Send response to inform_(un)lock, lock_device, fix #1075

src/BleDev.cpp, src/BleDev.h
If device in No Bundle state and user press Ctrl button during clicking on "Select Bundle File" then serial number and bundle is not checked.
=> [BLE] Fetch and send password for special no bundle upload

src/MPDevice.cpp, src/MPDevice.h
Remove empty service during integrity check from #1127
And remove empty parent if there is no renamed child for the given service.
=> [BLE] Remove empty service during integrity check, fix #1127

data/moolticute.desktop, gui.pro
To be merged after #1130, otherwise builds for the debian package will be broken (`PREFIX` will not be replaced).
Depending on how moolticute is installed or which distribution one uses, the moolticute executable might not be located in `/usr/bin`. For example, the nix package manager installes packages under `/nix/store`. This would also fix manual installs in `/usr/local`.
=> Generate Exec in moolticute.desktop during build

src/CredentialsManagement.cpp, src/CredentialsManagement.h, src/CredentialsManagement.ui
Login input size was incorrect fixing #1030 with it.
In case of long login or password pasted or typed display a warning red border instead of truncating the text, fix #1068:
=> Fix Login and Password length limit on Credentials tab, fix #1030

src/MainWindow.cpp, src/MainWindow.ui
=> Remove CTRL from shortcut displayed on Advanced tab

src/NotesManagement.cpp, src/NotesManagement.h
If note name is too long, align left.
Decrease note name size.
=> [BLE] Improve notes label name display

src/Common.cpp, src/Common.h, src/CredentialModel.cpp, src/CredentialsManagement.cpp, src/CredentialsManagement.h, src/MPDevice.cpp
- Changing password for multiple domain failed, fix with storing service with first tld from multiple domain list
- We have a multiple domain service e.g.: gmail [.com,.de], if I add a new credential in MMM for service 'gmail.hu' instead of adding new gmail.hu service add '.hu' to "gmail [.com,.de]".
=> [BLE] Multiple domain improvements

src/MPDevice.cpp
Earlier we added the credential to `mmmPasswordChangeArray` even if password was empty and later password save message was sent to device.
Prevent this with a condition for empty password.
=> [BLE] Fix sending save password for empty password

gui.pro
This PR add's missing files to the qmake install set and replaces `cp` with `INSTALL_FILE` to preserve access/modification times and set the mode correctly.
This is a draft PR, because I haven't had time yet to check everything, and to encourage others to add corrections.
=> Improve qmake install

tests/tests.pro
`make check` currently only builds the tests. Marking the app as a `testcase` ensures that the tests are actually run with `make check`.
`no_testcase_installs` prevents the test from being installed.
Docs: https://doc.qt.io/qt-5/qtest-overview.html#building-with-qmake
Sidenote: some tests, such as FilesCacheTests, are not enabled. Is this intended?
=> Run tests on `make check`

src/AppGui.cpp
The Qt6 versions of Moolticute on KDE fails to launch due to the workaround in #972. I tried to reproduce the issue this workaround should fix on multiple builds and systems, but failed to so.
This PR removes that workaround.
=> Remove window size workaround on Unix

win/installer.iss
Some users may want to install moolticute in an unattended silent way, e.g. the following installs in silent mode skipping the creation of a desktop icon:
setupfile.exe /VERYSILENT /TASKS="!desktopicon"
However this will still run programs in the `RUN` section which executes moolticute. This is undesired in an unattended setup, so we skip this [on silent installs][1].
NOTE: My change is based on the innosetup documentation but I did not run a build myself off this commit since I have no prior experience with innosetup.
[1]: https://documentation.help/Inno-Setup/topic_runsection.htm#skipifsilent
=> Allow silent install without application launch

src/CredentialsManagement.cpp
In MMM when user retrieves the password (with eye icon) it is fetching from device.
With adding the condition, if the given password was changed in MMM earlier, then the changed password is displayed.
=> Display changed password in MMM, fix #1217

src/AppGui.cpp, src/SystemNotifications/SystemNotificationWindows.cpp, src/SystemNotifications/SystemNotificationWindows.h
For Win10 notifications were not working, because the usage for QProcess start got deprecated, so switched to https://doc.qt.io/qt-6/qprocess.html#start.
Fixed focus assist and win10/11 detection too.
Tested on Win10 and Win11.
=> Fix SnoreToast notifications for Win10

src/MPDevice.cpp
During setting TOTP for credential with multiple domains we need to append the first domain to service name. (Just like during setting password  #1182)
=> Fix adding TOTP for multiple domain service

src/WSClient.cpp
Mentioned in #1219.
In CSV when service is separated by ',' add login and password for these multiple services.
=> Add support for multi-url CSV import

gui.pro
Add the `use_system_qzxing` option to conditionally use the system-provided QZXing instead of the bundled version. The bundled version will be used by default.
=> Add option to use shared or bundled QZXing

src/SystemNotifications/SystemNotificationWindows.cpp, src/SystemNotifications/SystemNotificationWindows.h
Instead of installing SnoreToast to Start Menu/Programs use it from installation folder.
=> Use SnoreToast from installed folder, fix #1238

lang/mc_br.ts, lang/mc_de.ts, lang/mc_fr.ts, lang/mc_hu.ts, lang/mc_ja.ts, lang/mc_ko.ts, lang/mc_nl.ts, lang/mc_pt.ts, lang/mc_ru.ts, lang/mc_sv.ts, lang/mc_tr.ts, src/MainWindow.cpp, src/MainWindow.h, src/MainWindow.ui
I have made a few mini bles for me and friends based on the available specs. As @limpkin suggested I used serial numbers >= 100000 for them. To avoid any frustration (in case any of the devices end up on ebay), I suggest treating any devices with serial number >=100000 as 'community creations'. For them: 
- Security challenge is disabled to avoid any irrelevant spam to the (unexpecting) original team,
- A warning is printed that the device is not affiliated with the original team. 
The translation files are updated yet again, I've added relevant Russian translation for the new messages and (hopefully) not too ugly German one. (The latter one needs some checking by some native speaker though, my knowledge of German is pretty bad).
=> Add 'Community creation' warning

src/BleDev.cpp
When loading the very first bundle into a freshly assembled DIY device wsClient->get_hwSerial() returns 0. On subsequent uploads the returned hwSerial is correct.  
Therefore the filename should be renamed 
from update_123456_from_bundle_0_to_1_xxxxxxxx.img to update_0_from_bundle_0_to_1_xxxxxxxx.img before moolticute will allow upload. This patch tells moolticute to treat hwSerial()==0 specially and allow bundle upload regardless of what serial number is specified in the filename.  For any hwSerial()!=0 the checks stay the same
=> BleDev: Fix handling of incorrect bundle version during initial bundle upload
